[package]
name = "certus-server-yaml"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
interfaces = { workspace = true, features = ["spdk"] }
component-framework.workspace = true
component-core.workspace = true
dispatcher = { workspace = true, default-features = false }
dispatcher-p2p = { workspace = true, default-features = false, optional = true }
dispatch-map.workspace = true
memory-tier.workspace = true
block-device-spdk-nvme = { workspace = true, optional = true }
block-device-filesys = { workspace = true, optional = true }
extent-manager.workspace = true
spdk-env = { workspace = true, optional = true }
gpu-services = { workspace = true, features = ["gpu"] }
logger.workspace = true

tonic = { version = "0.12", features = ["tls"] }
prost = "0.13"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
libc = "0.2"

[features]
default = ["spdk"]
spdk = ["spdk-mem", "dep:block-device-spdk-nvme", "dispatcher/spdk-backend"]
spdk-mem = ["dep:spdk-env"]
filesys = ["dep:block-device-filesys", "spdk-mem"]
p2p-native = ["dep:dispatcher-p2p", "spdk", "gpu-services/p2p", "dispatcher-p2p/spdk-backend"]

[build-dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
tonic-build = "0.12"
