use std::any::TypeId;

/// Marker trait for all framework interfaces.
///
/// All user-defined interfaces extend this trait implicitly via the
/// `define_interface!` macro. It enforces `Send + Sync + 'static`
/// bounds required for thread-safe composition and `TypeId`-based lookup.
///
/// # Examples
///
/// ```
/// use component_core::interface::Interface;
///
/// // A manual interface implementation (normally generated by macro):
/// trait IExample: Interface {
///     fn example(&self);
/// }
/// ```
pub trait Interface: Send + Sync + 'static {}

/// Metadata about a provided interface on a component.
///
/// Used by [`IUnknown::provided_interfaces`](crate::iunknown::IUnknown::provided_interfaces)
/// for runtime introspection.
///
/// # Examples
///
/// ```
/// use component_core::interface::InterfaceInfo;
/// use std::any::TypeId;
///
/// let info = InterfaceInfo {
///     type_id: TypeId::of::<u32>(), // placeholder for demo
///     name: "IExample",
/// };
/// assert_eq!(info.name, "IExample");
/// ```
#[derive(Debug, Clone)]
pub struct InterfaceInfo {
    /// Unique identity of the interface, derived from `TypeId::of::<dyn IFoo + Send + Sync>()`.
    pub type_id: TypeId,
    /// Human-readable name of the interface (e.g., `"IStorage"`).
    pub name: &'static str,
}

/// Metadata about a required interface (receptacle) on a component.
///
/// Used by [`IUnknown::receptacles`](crate::iunknown::IUnknown::receptacles)
/// for runtime introspection.
///
/// # Examples
///
/// ```
/// use component_core::interface::ReceptacleInfo;
/// use std::any::TypeId;
///
/// let info = ReceptacleInfo {
///     type_id: TypeId::of::<u32>(), // placeholder for demo
///     name: "logger",
///     interface_name: "ILogger",
/// };
/// assert_eq!(info.name, "logger");
/// assert_eq!(info.interface_name, "ILogger");
/// ```
#[derive(Debug, Clone)]
pub struct ReceptacleInfo {
    /// `TypeId` of the required interface trait object.
    pub type_id: TypeId,
    /// Human-readable name of the receptacle slot (e.g., `"logger"`).
    pub name: &'static str,
    /// Human-readable name of the required interface type (e.g., `"ILogger"`).
    pub interface_name: &'static str,
}
