(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require int.Int.
Require int.Abs.
Require int.EuclideanDivision.
Require Import Lia.

(* Why3 goal *)
Theorem mod_sub :
  forall (a:Numbers.BinNums.Z) (b:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (0%Z < n)%Z -> ((int.EuclideanDivision.mod1 a n) = 0%Z) ->
  ((int.EuclideanDivision.mod1 b n) = 0%Z) ->
  ((int.EuclideanDivision.mod1 (a - b)%Z n) = 0%Z).
Proof.
intros a b n h1 h2 h3.
(* Step 1: unfold mod1 in hypotheses only to expose the arithmetic.
   mod1 x y = x - y * div x y
   h2: a - n * div a n = 0  =>  a is a multiple of n
   h3: b - n * div b n = 0  =>  b is a multiple of n              *)
unfold int.EuclideanDivision.mod1 in h2, h3.
assert (Ha: (a = n * int.EuclideanDivision.div a n)%Z) by lia.
assert (Hb: (b = n * int.EuclideanDivision.div b n)%Z) by lia.
(* Step 2: a - b = n * k + 0  where k = div a n - div b n         *)
assert (Hab: (a - b =
    n * (int.EuclideanDivision.div a n - int.EuclideanDivision.div b n)
    + 0)%Z).
{ rewrite Ha at 1. rewrite Hb at 1. ring. }
(* Step 3: rewrite the goal using Hab, then apply Mod_mult.
   Mod_mult n k 0 h1: mod1 (n*k + 0) n = mod1 0 n
   Mod_0 (n≠0):       mod1 0 n = 0                                *)
rewrite Hab.
rewrite (int.EuclideanDivision.Mod_mult
           n
           (int.EuclideanDivision.div a n - int.EuclideanDivision.div b n)
           0
           h1).
apply int.EuclideanDivision.Mod_0.
lia.
Qed.
