#!/usr/bin/env python3
"""Generate src/proofs_component_mutants.rs: one `__mutant` anti-vacuity twin per listed
`verify_<id>` harness in src/proofs_component.rs.

THE ONE CHANGE. Each twin is a verbatim copy of its base harness (same attributes, same
setup, same calls into the real component) in which exactly ONE assertion is replaced by
its negation: by default the LAST top-level `assert!(..)` of the body, i.e. the furthest
point of the harness. Under `--unwind N --no-unwinding-checks` CBMC may PRUNE paths; a base
harness whose paths were all pruned passes with no content. Its twin then also passes,
because a negated assertion on an unreachable point is just as vacuously true. If the twin
FAILS, CBMC found an execution that reaches the end of the harness with every earlier
assertion of the base holding and the final postcondition provably TRUE there (its
negation is refuted) — so the base proof has content.

OVERRIDES pick a different single assertion where the last one is inside a branch or is
not the obligation's own postcondition; each override says why.

Regenerate after editing a base harness:  python3 gen_component_mutants.py
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "src" / "proofs_component.rs"
OUT = HERE / "src" / "proofs_component_mutants.rs"
IDS = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/tmp/epo_51_unvouched.txt")

# id-harness -> exact text of the assertion line (stripped) to negate instead of the last one.
OVERRIDES = {
    # last assert sits in the `else` branch; negate the created-pool branch's postcondition,
    # which is the one that needs the pool to have been reached through track + evict.
    "verify_epo_evict_pre_total": "assert!(r == Some(A));",
}


def harness_name(pid):
    return "verify_" + pid.lower().replace("-", "_")


def extract(txt, name):
    """Return (attrs_text, body_text) of `fn name()` — attributes = the contiguous
    #[...] lines directly above it (doc comments dropped)."""
    m = re.search(r"^fn " + re.escape(name) + r"\(\) \{\n", txt, re.M)
    if not m:
        raise SystemExit(f"harness {name} not found")
    # attributes above
    head = txt[: m.start()].splitlines()
    attrs = []
    while head and head[-1].startswith("#["):
        attrs.insert(0, head.pop())
    # body by brace matching from the opening brace
    i = m.end() - 2  # at '{'
    depth = 0
    j = i
    while True:
        ch = txt[j]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                break
        j += 1
    body = txt[m.end(): j]  # between braces, excluding them
    return "\n".join(attrs), body


ASSERT_RE = re.compile(r"^(    )assert!\((.*)\);\s*(//.*)?$")


def mutate(name, body):
    lines = body.split("\n")
    target = OVERRIDES.get(name)
    idx, inner = None, None
    for k, ln in enumerate(lines):
        if target is not None:
            if ln.strip().startswith(target):
                if idx is not None:
                    raise SystemExit(f"{name}: override line not unique")
                idx = k
                m = re.match(r"^\s*assert!\((.*)\);\s*(//.*)?$", ln)
                inner = m.group(1)
        else:
            m = ASSERT_RE.match(ln)
            if m:
                idx, inner = k, m.group(2)  # keep the LAST top-level single-line assert
    if idx is None:
        raise SystemExit(f"{name}: no assertion to negate")
    ln = lines[idx]
    indent = ln[: len(ln) - len(ln.lstrip())]
    lines[idx] = f"{indent}assert!(!({inner})); // MUTANT: negated"
    return "\n".join(lines), inner


def main():
    txt = SRC.read_text()
    ids = [l.strip() for l in IDS.read_text().splitlines() if l.strip()]
    out = [
        "// GENERATED by ../gen_component_mutants.py — do not edit by hand; regenerate instead.",
        "//",
        "// Anti-vacuity twins for the real-component harnesses in proofs_component.rs. Each",
        "// `verify_<id>__mutant` is its base harness verbatim with ONE assertion negated (see the",
        "// generator's docstring). The gate requires every twin to FAIL under the same flags the",
        "// base proved with (`--unwind 4 --no-unwinding-checks`, and `--unwind 8` if escalated).",
        "",
        "use crate::api::*;",
        "",
        "const A: CacheKey = 10;",
        "const B: CacheKey = 20;",
        "const C: CacheKey = 30;",
        "const D: CacheKey = 40;",
        "",
    ]
    table = []
    for pid in ids:
        name = harness_name(pid)
        attrs, body = extract(txt, name)
        mbody, inner = mutate(name, body)
        out.append(f"/// Twin of `{name}` ({pid}): negates `{inner}`. Must FAIL.")
        out.append(attrs)
        out.append(f"fn {name}__mutant() {{\n{mbody}}}\n")
        table.append((pid, inner))
    OUT.write_text("\n".join(out))
    for pid, inner in table:
        print(f"{pid}\t{inner}")
    print(f"wrote {len(table)} twins -> {OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
