use std::any::{Any, TypeId};
use std::sync::Arc;

use crate::error::RegistryError;
use crate::interface::{InterfaceInfo, ReceptacleInfo};

/// Base interface for all components. Provides introspection.
///
/// Every component MUST implement `IUnknown`. The `define_component!`
/// macro generates this implementation automatically.
///
/// The trait is object-safe: all methods are non-generic. For typed
/// interface queries, use the [`query`] free function.
///
/// # Examples
///
/// ```
/// use component_core::iunknown::IUnknown;
/// use component_core::interface::{InterfaceInfo, ReceptacleInfo};
/// use std::any::{Any, TypeId};
///
/// // A minimal manual IUnknown implementation for demonstration:
/// struct DemoComponent;
///
/// impl IUnknown for DemoComponent {
///     fn query_interface_raw(&self, _id: TypeId) -> Option<&(dyn Any + Send + Sync)> {
///         None
///     }
///     fn version(&self) -> &str { "0.1.0" }
///     fn provided_interfaces(&self) -> &[InterfaceInfo] { &[] }
///     fn receptacles(&self) -> &[ReceptacleInfo] { &[] }
///     fn connect_receptacle_raw(&self, _name: &str, _provider: &dyn IUnknown) -> Result<(), component_core::error::RegistryError> {
///         Err(component_core::error::RegistryError::BindingFailed { detail: "no receptacles".into() })
///     }
/// }
///
/// let comp = DemoComponent;
/// assert_eq!(comp.version(), "0.1.0");
/// ```
pub trait IUnknown: Send + Sync {
    /// Look up an interface by `TypeId`.
    ///
    /// Returns a type-erased reference that the caller downcasts to
    /// `&Arc<dyn IFoo + Send + Sync>` using `downcast_ref`.
    ///
    /// Returns `None` if the interface is not provided.
    fn query_interface_raw(&self, id: TypeId) -> Option<&(dyn Any + Send + Sync)>;

    /// Component version string (e.g., `"1.2.0"`).
    fn version(&self) -> &str;

    /// List of all interfaces this component provides.
    ///
    /// The list always includes `IUnknown` itself when generated by
    /// `define_component!`.
    ///
    /// # Examples
    ///
    /// ```
    /// use component_core::iunknown::IUnknown;
    /// use component_core::interface::{InterfaceInfo, ReceptacleInfo};
    /// use std::any::{Any, TypeId};
    ///
    /// struct Demo {
    ///     infos: Vec<InterfaceInfo>,
    /// }
    ///
    /// impl IUnknown for Demo {
    ///     fn query_interface_raw(&self, _id: TypeId) -> Option<&(dyn Any + Send + Sync)> { None }
    ///     fn version(&self) -> &str { "1.0.0" }
    ///     fn provided_interfaces(&self) -> &[InterfaceInfo] { &self.infos }
    ///     fn receptacles(&self) -> &[ReceptacleInfo] { &[] }
    ///     fn connect_receptacle_raw(&self, _name: &str, _provider: &dyn IUnknown) -> Result<(), component_core::error::RegistryError> {
    ///         Err(component_core::error::RegistryError::BindingFailed { detail: "no receptacles".into() })
    ///     }
    /// }
    ///
    /// let comp = Demo {
    ///     infos: vec![InterfaceInfo {
    ///         type_id: TypeId::of::<()>(),
    ///         name: "IUnknown",
    ///     }],
    /// };
    /// assert_eq!(comp.provided_interfaces().len(), 1);
    /// assert_eq!(comp.provided_interfaces()[0].name, "IUnknown");
    /// ```
    fn provided_interfaces(&self) -> &[InterfaceInfo];

    /// List of all receptacles (required interfaces) on this component.
    ///
    /// Returns an empty slice if the component has no receptacles.
    ///
    /// # Examples
    ///
    /// ```
    /// use component_core::iunknown::IUnknown;
    /// use component_core::interface::{InterfaceInfo, ReceptacleInfo};
    /// use std::any::{Any, TypeId};
    ///
    /// struct Demo;
    ///
    /// impl IUnknown for Demo {
    ///     fn query_interface_raw(&self, _id: TypeId) -> Option<&(dyn Any + Send + Sync)> { None }
    ///     fn version(&self) -> &str { "1.0.0" }
    ///     fn provided_interfaces(&self) -> &[InterfaceInfo] { &[] }
    ///     fn receptacles(&self) -> &[ReceptacleInfo] { &[] }
    ///     fn connect_receptacle_raw(&self, _name: &str, _provider: &dyn IUnknown) -> Result<(), component_core::error::RegistryError> {
    ///         Err(component_core::error::RegistryError::BindingFailed { detail: "no receptacles".into() })
    ///     }
    /// }
    ///
    /// let comp = Demo;
    /// assert!(comp.receptacles().is_empty());
    /// ```
    fn receptacles(&self) -> &[ReceptacleInfo];

    /// Connect a named receptacle to an interface from the given provider.
    ///
    /// Used by third-party binding to wire components by string names.
    /// The implementation (generated by `define_component!`) matches the
    /// receptacle name, queries the provider for the matching interface
    /// type, and connects the receptacle.
    ///
    /// Returns `Err(RegistryError::BindingFailed)` if the receptacle name
    /// is unknown, the provider doesn't offer the needed interface, or the
    /// receptacle is already connected.
    fn connect_receptacle_raw(
        &self,
        receptacle_name: &str,
        provider: &dyn IUnknown,
    ) -> Result<(), RegistryError>;
}

/// Typed wrapper for [`IUnknown::query_interface_raw`].
///
/// Looks up interface `I` on the given `IUnknown` implementor and
/// returns a cloned `Arc<I>` if the component provides it.
///
/// # Type Parameters
///
/// * `I` — The interface trait object type, e.g., `dyn IStorage + Send + Sync`.
///   Must be `Send + Sync + 'static` so that `Arc<I>` implements `Any`.
///
/// # Examples
///
/// ```
/// use component_core::iunknown::{IUnknown, query};
/// use component_core::interface::{InterfaceInfo, ReceptacleInfo};
/// use std::any::{Any, TypeId};
/// use std::sync::Arc;
///
/// trait IGreeter: Send + Sync {
///     fn greet(&self) -> &str;
/// }
///
/// struct MyComponent {
///     greeter: Arc<dyn IGreeter + Send + Sync>,
/// }
///
/// impl IUnknown for MyComponent {
///     fn query_interface_raw(&self, id: TypeId) -> Option<&(dyn Any + Send + Sync)> {
///         if id == TypeId::of::<Arc<dyn IGreeter + Send + Sync>>() {
///             Some(&self.greeter)
///         } else {
///             None
///         }
///     }
///     fn version(&self) -> &str { "1.0.0" }
///     fn provided_interfaces(&self) -> &[InterfaceInfo] { &[] }
///     fn receptacles(&self) -> &[ReceptacleInfo] { &[] }
///     fn connect_receptacle_raw(&self, _name: &str, _provider: &dyn IUnknown) -> Result<(), component_core::error::RegistryError> {
///         Err(component_core::error::RegistryError::BindingFailed { detail: "no receptacles".into() })
///     }
/// }
///
/// struct Greeter;
/// impl IGreeter for Greeter {
///     fn greet(&self) -> &str { "hello" }
/// }
///
/// let comp = MyComponent {
///     greeter: Arc::new(Greeter),
/// };
///
/// let g: Arc<dyn IGreeter + Send + Sync> =
///     query::<dyn IGreeter + Send + Sync>(&comp).unwrap();
/// assert_eq!(g.greet(), "hello");
/// ```
pub fn query<I: Send + Sync + 'static + ?Sized>(component: &dyn IUnknown) -> Option<Arc<I>>
where
    Arc<I>: Any + Send + Sync,
{
    let type_id = TypeId::of::<Arc<I>>();
    let any_ref = component.query_interface_raw(type_id)?;
    let arc_ref = any_ref.downcast_ref::<Arc<I>>()?;
    Some(Arc::clone(arc_ref))
}

/// Convenience macro for querying an interface from a component.
///
/// Eliminates the need to spell out `dyn Trait + Send + Sync` and the
/// `&*` deref when querying from an `Arc`.
///
/// Works with any type implementing `IUnknown`: `Arc<T>`, `&T`, or `T`
/// directly. Uses `AsRef<dyn IUnknown>`-style coercion via Deref or
/// direct reference.
///
/// # Syntax
///
/// ```text
/// query_interface!(component, InterfaceName)
/// ```
///
/// # Examples
///
/// ```
/// use component_core::iunknown::{IUnknown, query};
/// use component_core::query_interface;
/// use component_core::interface::{InterfaceInfo, ReceptacleInfo};
/// use std::any::{Any, TypeId};
/// use std::sync::Arc;
///
/// trait IGreeter: Send + Sync {
///     fn greet(&self) -> &str;
/// }
///
/// struct MyComponent {
///     greeter: Arc<dyn IGreeter + Send + Sync>,
/// }
///
/// impl IUnknown for MyComponent {
///     fn query_interface_raw(&self, id: TypeId) -> Option<&(dyn Any + Send + Sync)> {
///         if id == TypeId::of::<Arc<dyn IGreeter + Send + Sync>>() {
///             Some(&self.greeter)
///         } else {
///             None
///         }
///     }
///     fn version(&self) -> &str { "1.0.0" }
///     fn provided_interfaces(&self) -> &[InterfaceInfo] { &[] }
///     fn receptacles(&self) -> &[ReceptacleInfo] { &[] }
///     fn connect_receptacle_raw(&self, _name: &str, _provider: &dyn IUnknown)
///         -> Result<(), component_core::error::RegistryError> {
///         Err(component_core::error::RegistryError::BindingFailed { detail: "none".into() })
///     }
/// }
///
/// struct Greeter;
/// impl IGreeter for Greeter {
///     fn greet(&self) -> &str { "hello" }
/// }
///
/// // Works with Arc<T>
/// let comp = Arc::new(MyComponent { greeter: Arc::new(Greeter) });
/// let g: Arc<dyn IGreeter + Send + Sync> = query_interface!(comp, IGreeter).unwrap();
/// assert_eq!(g.greet(), "hello");
///
/// // Also works with direct reference
/// let g2: Arc<dyn IGreeter + Send + Sync> = query_interface!(&*comp, IGreeter).unwrap();
/// assert_eq!(g2.greet(), "hello");
/// ```
#[macro_export]
macro_rules! query_interface {
    ($component:expr, $iface:path) => {{
        use $crate::iunknown::AsIUnknown as _;
        $crate::iunknown::query::<dyn $iface + Send + Sync>(($component).__as_iunknown())
    }};
}

/// Helper trait for the `query_interface!` macro to accept various container types.
#[doc(hidden)]
pub trait AsIUnknown {
    fn __as_iunknown(&self) -> &dyn IUnknown;
}

impl<T: IUnknown> AsIUnknown for T {
    fn __as_iunknown(&self) -> &dyn IUnknown {
        self
    }
}

impl<T: IUnknown> AsIUnknown for Arc<T> {
    fn __as_iunknown(&self) -> &dyn IUnknown {
        &**self
    }
}

impl AsIUnknown for crate::component_ref::ComponentRef {
    fn __as_iunknown(&self) -> &dyn IUnknown {
        &**self
    }
}
