//! Kani harnesses at the component / `IEvictionPolicy` boundary.
//!
//! This is a CHILD module of the crate root, so it can read `EvictionState`'s
//! private `announced` latch and the `state` / `logger` fields generated by
//! `define_component!`. Wired from `src/lib.rs` with
//! `#[cfg(kani)] #[path = "../verif-kani/component_harnesses.rs"] mod component_harnesses;`
//! so all harness code lives outside `src/`.
//!
//! Geometry: the REAL component is built with `new_default()` (so the generated
//! interface map, the `RwLock<EvictionState>` and the per-pool `Mutex<Pool>` are
//! all in situ) with `RandomState::new` stubbed to a fixed `[0,0]` seed. Pools hold
//! 1-3 blocks so every invariant loop is covered at unwind 4. See
//! `pool_harnesses.rs` for why the sound bound is >= 6 and why the gate's
//! `--no-unwinding-checks` lever (bounded-shallow) is the affordable claim here.

#![allow(dead_code, unused_imports, unused_variables, unused_mut)]

use super::{EvictionPolicySessionListsComponent, EvictionState};
use interfaces::{
    BlockSemantics, CacheKey, EvictionHandle, EvictionPolicyError, IEvictionPolicy, ILogger, PoolId,
};
use std::collections::hash_map::RandomState;
use std::mem::transmute;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::Arc;

use crate::session_list::pool_harnesses::{
    active_at, check_inv, child_at, clock_of, has_key, ix_of, key_at, leaves_len, parent_at,
    session_at, slots_of, stamp_at,
};

/// Deterministic `RandomState` — defeats KD-HASHMAP-RANDOMSTATE.
pub fn concrete_state() -> RandomState {
    let keys: [u64; 2] = [0, 0];
    unsafe { transmute(keys) }
}

fn comp() -> Arc<EvictionPolicySessionListsComponent> {
    EvictionPolicySessionListsComponent::new_default()
}

fn sem(s: u64) -> BlockSemantics {
    BlockSemantics { session_id: s }
}

/// A symbolic pool id that is guaranteed NOT to name an existing pool.
fn any_bad_pool(existing: u32) -> PoolId {
    let p: PoolId = kani::any();
    kani::assume(p >= existing);
    p
}

/// A symbolic arena index in range for a <= 3 slot pool.
fn any_ix() -> u32 {
    let i: u32 = kani::any();
    kani::assume(i < 4);
    i
}


/// Faithful element-wise model of `core::ptr::swap_nonoverlapping`. The real
/// implementation swaps through fixed 8-byte chunks, so its inner loop runs
/// `size_of::<T>() / 8` times whatever the data size -- 6 iterations for `Node`,
/// which is the loop that puts unwinding checks out of reach here (MEASURED: one
/// `register` closes at unwind 6 in 253 s, and at unwind 4 with this model in
/// 177 s). The model performs exactly the same memory effect with a
/// `count`-length loop (`count` is 1 at every call site reached), so no unwind
/// budget is spent on a byte-chunking detail. Disclosed stub -> symbol *.
unsafe fn swap_nonoverlapping_model<T>(x: *mut T, y: *mut T, count: usize) {
    let mut i = 0usize;
    while i < count {
        let t = std::ptr::read(x.add(i));
        std::ptr::write(x.add(i), std::ptr::read(y.add(i)));
        std::ptr::write(y.add(i), t);
        i += 1;
    }
}

/// Counts the `info` announcements so "at most once" is observable.
struct CountingLogger {
    infos: AtomicUsize,
}

impl ILogger for CountingLogger {
    fn error(&self, _msg: &str) {}
    fn warn(&self, _msg: &str) {}
    fn info(&self, _msg: &str) {
        self.infos.fetch_add(1, Ordering::SeqCst);
    }
    fn debug(&self, _msg: &str) {}
}

// ===========================================================================
// Smoke / wiring
// ===========================================================================

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn smoke_component_builds() {
    let c = comp();
    let p = c.create_pool();
    assert!(p == 0);
    assert!(c.len(p) == 0);
}

// ===========================================================================
// create_pool
// ===========================================================================

// EPSL-CREATE-POOL-STARTS-EMPTY
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_create_pool_starts_empty() {
    let c = comp();
    let p = c.create_pool();
    assert!(c.len(p) == 0);
    assert!(c.identify_next_to_evict(p).is_none());
    assert!(c.get_eviction_candidates(p, 4).is_empty());
    assert!(c.get_eviction_candidates(p, 0).is_empty());
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_create_pool_starts_empty__mutant() {
    // WRONG: claims a fresh domain already has something to evict.
    let c = comp();
    let p = c.create_pool();
    assert!(c.identify_next_to_evict(p).is_some());
}

// EPSL-CREATE-POOL-ISSUES-A-FRESH-SEQUENTIAL-IDENTIFIER
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_create_pool_issues_a_fresh_sequential_identifier() {
    let c = comp();
    let a = c.create_pool();
    let b = c.create_pool();
    let d = c.create_pool();
    // start at zero, count upwards, no gaps, no reuse
    assert!(a == 0);
    assert!(b == 1);
    assert!(d == 2);
    assert!(a != b && b != d && a != d);
    // the identifier handed back is the number of domains that existed before
    assert!(c.state.read().unwrap().pools.len() == 3);
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_create_pool_issues_a_fresh_sequential_identifier__mutant() {
    // WRONG: claims identifiers are reused.
    let c = comp();
    let a = c.create_pool();
    let b = c.create_pool();
    assert!(a == b);
}

// EPSL-CREATE-POOL-PRESERVES-EXISTING-POOLS
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_create_pool_preserves_existing_pools() {
    let c = comp();
    let pa = c.create_pool();
    let h1 = c.track(pa, 10, sem(1)).unwrap();
    let h2 = c.track(pa, 20, sem(1)).unwrap();
    let len_before = c.len(pa);
    let cands_before = c.get_eviction_candidates(pa, 4);
    let pb = c.create_pool();
    // pa still names the same domain with the same contents
    assert!(c.len(pa) == len_before);
    let cands_after = c.get_eviction_candidates(pa, 4);
    assert!(cands_after.len() == cands_before.len());
    for k in 0..cands_after.len() {
        assert!(cands_after[k] == cands_before[k]);
    }
    // its handles still work and still name their blocks
    assert!(c.touch(h1) == Ok(()));
    assert!(c.touch(h2) == Ok(()));
    assert!(pb != pa);
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_create_pool_preserves_existing_pools__mutant() {
    // WRONG: claims creating a domain empties the existing one.
    let c = comp();
    let pa = c.create_pool();
    c.track(pa, 10, sem(1)).unwrap();
    c.create_pool();
    assert!(c.len(pa) == 0);
}

// EPSL-CREATE-POOL-ANNOUNCES-AT-MOST-ONCE
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_create_pool_announces_at_most_once() {
    let c = comp();
    let lg = Arc::new(CountingLogger {
        infos: AtomicUsize::new(0),
    });
    let dynlg: Arc<dyn ILogger + Send + Sync> = lg.clone();
    assert!(c.logger.connect(dynlg).is_ok());
    c.create_pool();
    assert!(lg.infos.load(Ordering::SeqCst) == 1);
    assert!(c.state.read().unwrap().announced);
    c.create_pool();
    c.create_pool();
    // however many domains are created, the one-off announcement fired once
    assert!(lg.infos.load(Ordering::SeqCst) == 1);
    assert!(c.state.read().unwrap().announced);
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_create_pool_announces_at_most_once__mutant() {
    // WRONG: claims the announcement fires once per domain.
    let c = comp();
    let lg = Arc::new(CountingLogger {
        infos: AtomicUsize::new(0),
    });
    let dynlg: Arc<dyn ILogger + Send + Sync> = lg.clone();
    assert!(c.logger.connect(dynlg).is_ok());
    c.create_pool();
    c.create_pool();
    assert!(lg.infos.load(Ordering::SeqCst) == 2);
}

// EPSL-ANNOUNCE-LATCH-SET-ONLY-WITH-A-LOGGER
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_announce_latch_set_only_with_a_logger() {
    let c = comp();
    // no logger attached: the latch is NOT consumed, however many domains are made
    c.create_pool();
    c.create_pool();
    assert!(!c.state.read().unwrap().announced);
    // and the announcement is still available once a logger arrives
    let lg = Arc::new(CountingLogger {
        infos: AtomicUsize::new(0),
    });
    let dynlg: Arc<dyn ILogger + Send + Sync> = lg.clone();
    assert!(c.logger.connect(dynlg).is_ok());
    c.create_pool();
    assert!(lg.infos.load(Ordering::SeqCst) == 1);
    assert!(c.state.read().unwrap().announced);
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_announce_latch_set_only_with_a_logger__mutant() {
    // WRONG: claims the latch is set even with no logger attached.
    let c = comp();
    c.create_pool();
    assert!(c.state.read().unwrap().announced);
}

// EPSL-POOL-COUNT-ASSUMED-BELOW-U32-MAX
#[kani::proof]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_pool_count_assumed_below_u32_max() {
    // The identifier is `state.pools.len() as u32`. Under the documented
    // assumption (fewer than u32::MAX domains) the cast is injective, so two
    // distinct domain counts can never yield the same identifier.
    let n: usize = kani::any();
    let m: usize = kani::any();
    kani::assume(n < u32::MAX as usize);
    kani::assume(m < u32::MAX as usize);
    kani::assume(n != m);
    assert!((n as u32) != (m as u32));
    assert!((n as u32) as usize == n);
}

#[kani::proof]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_pool_count_assumed_below_u32_max__mutant() {
    // WRONG: drops the assumption, so identifiers can repeat.
    let n: usize = kani::any();
    let m: usize = kani::any();
    kani::assume(n != m);
    assert!((n as u32) != (m as u32));
}

// ===========================================================================
// track at the component boundary
// ===========================================================================

// EPSL-TRACK-RETURNS-USABLE-HANDLE
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_track_returns_usable_handle() {
    let c = comp();
    let p = c.create_pool();
    let h = c.track(p, 10, sem(1)).unwrap();
    // the handle carries the domain the caller named plus the storage position
    assert!(h.pool_id() == p);
    assert!(h.index() == 0);
    assert!(h == EvictionHandle::new(p, 0));
    // and those two pieces are exactly what a later refresh / stop-tracking uses
    assert!(c.touch(h) == Ok(()));
    assert!(c.remove(h) == Ok(()));
    assert!(c.len(p) == 0);
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_track_returns_usable_handle__mutant() {
    // WRONG: claims the handle names a different domain.
    let c = comp();
    let p = c.create_pool();
    let q = c.create_pool();
    let h = c.track(p, 10, sem(1)).unwrap();
    assert!(h.pool_id() == q);
}

// EPSL-TRACK-UNKNOWN-DOMAIN-IS-AN-ERROR
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_track_unknown_domain_is_an_error() {
    let c = comp();
    let p = c.create_pool();
    c.track(p, 10, sem(1)).unwrap();
    let bad = any_bad_pool(1);
    let r = c.track(bad, 20, sem(2));
    assert!(r == Err(EvictionPolicyError::InvalidPool(bad)));
    // and the existing domain is exactly as it was
    assert!(c.len(p) == 1);
    assert!(c.get_eviction_candidates(p, 4)[0] == 10);
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_track_unknown_domain_is_an_error__mutant() {
    // WRONG: claims registering into a non-existent domain succeeds.
    let c = comp();
    c.create_pool();
    assert!(c.track(7, 20, sem(2)).is_ok());
}

// EPSL-TRACK-NEVER-REPORTS-INVALID-HANDLE
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_track_never_reports_invalid_handle() {
    let c = comp();
    c.create_pool();
    let p: PoolId = kani::any();
    kani::assume(p < 3); // covers the one live domain and two unknown ones
    let r = c.track(p, 10, sem(1));
    match r {
        Ok(_) => assert!(p == 0),
        Err(EvictionPolicyError::InvalidPool(id)) => assert!(id == p),
        Err(EvictionPolicyError::InvalidHandle) => assert!(false),
    }
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_track_never_reports_invalid_handle__mutant() {
    // WRONG: claims registration reports the invalid-handle error.
    let c = comp();
    c.create_pool();
    assert!(c.track(5, 10, sem(1)) == Err(EvictionPolicyError::InvalidHandle));
}

// EPSL-TRACK-KEYS-ARE-SCOPED-TO-ONE-POOL
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_track_keys_are_scoped_to_one_pool() {
    let c = comp();
    let pa = c.create_pool();
    let pb = c.create_pool();
    // the SAME key tracked independently in two domains
    let ha = c.track(pa, 10, sem(1)).unwrap();
    let hb = c.track(pb, 10, sem(9)).unwrap();
    assert!(ha != hb);
    assert!(ha.pool_id() == pa && hb.pool_id() == pb);
    assert!(c.len(pa) == 1 && c.len(pb) == 1);
    // each domain holds its own block for that key, with its own session and place
    let ga = c.state.read().unwrap();
    {
        let a = ga.pools[pa as usize].lock().unwrap();
        let b = ga.pools[pb as usize].lock().unwrap();
        let ia = ix_of(&a, 10);
        let ib = ix_of(&b, 10);
        assert!(session_at(&a, ia) == 1);
        assert!(session_at(&b, ib) == 9);
    }
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_track_keys_are_scoped_to_one_pool__mutant() {
    // WRONG: claims the second domain treats the key as already tracked.
    let c = comp();
    let pa = c.create_pool();
    let pb = c.create_pool();
    c.track(pa, 10, sem(1)).unwrap();
    c.track(pb, 10, sem(9)).unwrap();
    assert!(c.len(pb) == 0);
}

// ===========================================================================
// handle-taking operations vs an unknown domain
// ===========================================================================

// EPSL-HANDLE-OPERATIONS-REJECT-UNKNOWN-DOMAIN
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_handle_operations_reject_unknown_domain() {
    let c = comp();
    let p = c.create_pool();
    c.track(p, 10, sem(1)).unwrap();
    let bad = any_bad_pool(1);
    let h = EvictionHandle::new(bad, any_ix());
    assert!(c.touch(h) == Err(EvictionPolicyError::InvalidPool(bad)));
    assert!(c.remove(h) == Err(EvictionPolicyError::InvalidPool(bad)));
    assert!(c.batch_touch(&[h]) == Err(EvictionPolicyError::InvalidPool(bad)));
    // nothing changed
    assert!(c.len(p) == 1);
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_handle_operations_reject_unknown_domain__mutant() {
    // WRONG: claims the invalid-handle error is reported for an unknown domain.
    let c = comp();
    c.create_pool();
    let h = EvictionHandle::new(9, 0);
    assert!(c.touch(h) == Err(EvictionPolicyError::InvalidHandle));
}

// EPSL-REMOVE-REJECTS-UNKNOWN-POOL
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_remove_rejects_unknown_pool() {
    let c = comp();
    let p = c.create_pool();
    let h = c.track(p, 10, sem(1)).unwrap();
    let bad = any_bad_pool(1);
    let stale = EvictionHandle::new(bad, 0);
    assert!(c.remove(stale) == Err(EvictionPolicyError::InvalidPool(bad)));
    // nothing anywhere changed
    assert!(c.len(p) == 1);
    assert!(c.touch(h) == Ok(()));
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_remove_rejects_unknown_pool__mutant() {
    // WRONG: claims the removal succeeds against an unknown domain.
    let c = comp();
    let p = c.create_pool();
    c.track(p, 10, sem(1)).unwrap();
    assert!(c.remove(EvictionHandle::new(4, 0)).is_ok());
}

// ===========================================================================
// batch_touch
// ===========================================================================

// EPSL-BATCH-TOUCH-REFRESHES-EVERY-BLOCK
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_batch_touch_refreshes_every_block() {
    let c = comp();
    let p = c.create_pool();
    let ha = c.track(p, 10, sem(1)).unwrap();
    let hb = c.track(p, 20, sem(2)).unwrap();
    let hc = c.track(p, 30, sem(3)).unwrap();
    // refresh the two OLDEST in one call; every member must be refreshed, not
    // just the first or the last
    assert!(c.batch_touch(&[ha, hb]) == Ok(()));
    let g = c.state.read().unwrap();
    let pool = g.pools[p as usize].lock().unwrap();
    let ia = ix_of(&pool, 10);
    let ib = ix_of(&pool, 20);
    let ic = ix_of(&pool, 30);
    assert!(stamp_at(&pool, ia) > stamp_at(&pool, ic));
    assert!(stamp_at(&pool, ib) > stamp_at(&pool, ic));
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_batch_touch_refreshes_every_block__mutant() {
    // WRONG: claims only the first member of the group is refreshed, so 20 would
    // still be older than 30.
    let c = comp();
    let p = c.create_pool();
    let ha = c.track(p, 10, sem(1)).unwrap();
    let hb = c.track(p, 20, sem(2)).unwrap();
    c.track(p, 30, sem(3)).unwrap();
    assert!(c.batch_touch(&[ha, hb]) == Ok(()));
    assert!(c.identify_next_to_evict(p) == Some(20));
}

// EPSL-BATCH-TOUCH-MATCHES-ONE-AT-A-TIME
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_batch_touch_matches_one_at_a_time() {
    // Two independent domains driven identically: one batched, one one-at-a-time.
    let c = comp();
    let pa = c.create_pool();
    let pb = c.create_pool();
    let a1 = c.track(pa, 10, sem(1)).unwrap();
    let a2 = c.track(pa, 20, sem(2)).unwrap();
    let b1 = c.track(pb, 10, sem(1)).unwrap();
    let b2 = c.track(pb, 20, sem(2)).unwrap();
    // a duplicate mention must end up with the recency of its LAST mention
    assert!(c.batch_touch(&[a1, a2, a1]) == Ok(()));
    assert!(c.touch(b1) == Ok(()));
    assert!(c.touch(b2) == Ok(()));
    assert!(c.touch(b1) == Ok(()));
    let ca = c.get_eviction_candidates(pa, 4);
    let cb = c.get_eviction_candidates(pb, 4);
    assert!(ca.len() == cb.len());
    for k in 0..ca.len() {
        assert!(ca[k] == cb[k]);
    }
    assert!(c.identify_next_to_evict(pa) == c.identify_next_to_evict(pb));
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_batch_touch_matches_one_at_a_time__mutant() {
    // WRONG: claims a duplicate mention keeps the recency of its FIRST mention,
    // so 10 would be evicted before 20.
    let c = comp();
    let p = c.create_pool();
    let h1 = c.track(p, 10, sem(1)).unwrap();
    let h2 = c.track(p, 20, sem(2)).unwrap();
    assert!(c.batch_touch(&[h1, h2, h1]) == Ok(()));
    assert!(c.identify_next_to_evict(p) == Some(10));
}

// EPSL-BATCH-TOUCH-TOUCHES-NOTHING-ELSE
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_batch_touch_touches_nothing_else() {
    let c = comp();
    let p = c.create_pool();
    let q = c.create_pool();
    let ha = c.track(p, 10, sem(1)).unwrap();
    let hb = c.track(p, 20, sem(2)).unwrap();
    let hq = c.track(q, 30, sem(3)).unwrap();
    let (sb, sq, lp, lq) = {
        let g = c.state.read().unwrap();
        let a = g.pools[p as usize].lock().unwrap();
        let b = g.pools[q as usize].lock().unwrap();
        let ib = ix_of(&a, 20);
        let iq = ix_of(&b, 30);
        (
            stamp_at(&a, ib),
            stamp_at(&b, iq),
            a.len(),
            b.len(),
        )
    };
    assert!(c.batch_touch(&[ha]) == Ok(()));
    let g = c.state.read().unwrap();
    let a = g.pools[p as usize].lock().unwrap();
    let b = g.pools[q as usize].lock().unwrap();
    let ib = ix_of(&a, 20);
    let iq = ix_of(&b, 30);
    // a block not named in the group keeps its recency; nothing is added/removed
    assert!(stamp_at(&a, ib) == sb);
    assert!(stamp_at(&b, iq) == sq);
    assert!(a.len() == lp);
    assert!(b.len() == lq);
    assert!(parent_at(&a, ib).is_none());
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_batch_touch_touches_nothing_else__mutant() {
    // WRONG: claims refreshing 10 also reorders 20 behind it.
    let c = comp();
    let p = c.create_pool();
    let ha = c.track(p, 10, sem(1)).unwrap();
    c.track(p, 20, sem(2)).unwrap();
    assert!(c.batch_touch(&[ha]) == Ok(()));
    assert!(c.identify_next_to_evict(p) == Some(10));
}

// EPSL-BATCH-TOUCH-REJECTS-UNKNOWN-POOL
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_batch_touch_rejects_unknown_pool() {
    let c = comp();
    let p = c.create_pool();
    let h = c.track(p, 10, sem(1)).unwrap();
    let bad = any_bad_pool(1);
    // the whole call fails with an invalid-domain error naming that identifier
    assert!(c.batch_touch(&[h, EvictionHandle::new(bad, 0)])
        == Err(EvictionPolicyError::InvalidPool(bad)));
    // and the check happened only when the walk REACHED that handle: the earlier
    // valid handle was already refreshed
    let g = c.state.read().unwrap();
    let pool = g.pools[p as usize].lock().unwrap();
    let i = ix_of(&pool, 10);
    assert!(stamp_at(&pool, i) == 2);
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_batch_touch_rejects_unknown_pool__mutant() {
    // WRONG: claims the unknown domain is caught up front, before the first
    // handle is refreshed.
    let c = comp();
    let p = c.create_pool();
    let h = c.track(p, 10, sem(1)).unwrap();
    let _ = c.batch_touch(&[h, EvictionHandle::new(5, 0)]);
    let g = c.state.read().unwrap();
    let pool = g.pools[p as usize].lock().unwrap();
    let i = ix_of(&pool, 10);
    assert!(stamp_at(&pool, i) == 1);
}

// EPSL-BATCH-TOUCH-EMPTY-SUCCEEDS-WITHOUT-VALIDATION
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_batch_touch_empty_succeeds_without_validation() {
    // A component with NO domains at all: an empty group still succeeds, which is
    // only possible because the early return happens before any lookup or lock.
    let c = comp();
    assert!(c.state.read().unwrap().pools.is_empty());
    let empty: [EvictionHandle; 0] = [];
    assert!(c.batch_touch(&empty) == Ok(()));
    assert!(c.state.read().unwrap().pools.is_empty());
    // and with a domain present, nothing changes either
    let p = c.create_pool();
    let h = c.track(p, 10, sem(1)).unwrap();
    let before = {
        let g = c.state.read().unwrap();
        let pool = g.pools[p as usize].lock().unwrap();
        let i = ix_of(&pool, 10);
        stamp_at(&pool, i)
    };
    assert!(c.batch_touch(&empty) == Ok(()));
    let g = c.state.read().unwrap();
    let pool = g.pools[p as usize].lock().unwrap();
    let i = ix_of(&pool, 10);
    assert!(stamp_at(&pool, i) == before);
    assert!(clock_of(&pool) == before);
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_batch_touch_empty_succeeds_without_validation__mutant() {
    // WRONG: claims an empty group on a component with no domains errors.
    let c = comp();
    let empty: [EvictionHandle; 0] = [];
    assert!(c.batch_touch(&empty).is_err());
}

// EPSL-BATCH-TOUCH-RELOCKS-WHEN-THE-POOL-CHANGES
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_batch_touch_relocks_when_the_pool_changes() {
    let c = comp();
    let pa = c.create_pool();
    let pb = c.create_pool();
    let a1 = c.track(pa, 10, sem(1)).unwrap();
    let a2 = c.track(pa, 11, sem(2)).unwrap();
    let b1 = c.track(pb, 20, sem(1)).unwrap();
    // a group that ALTERNATES domains: pa, pb, pa -> the component must change
    // domain on every step and each block is refreshed in its own domain
    assert!(c.batch_touch(&[a1, b1, a2]) == Ok(()));
    let g = c.state.read().unwrap();
    let a = g.pools[pa as usize].lock().unwrap();
    let b = g.pools[pb as usize].lock().unwrap();
    let i10 = ix_of(&a, 10);
    let i11 = ix_of(&a, 11);
    let i20 = ix_of(&b, 20);
    // pa's clock advanced twice, pb's once -- each in its own domain
    assert!(clock_of(&a) == 4);
    assert!(clock_of(&b) == 2);
    assert!(stamp_at(&a, i11) > stamp_at(&a, i10));
    assert!(stamp_at(&b, i20) == 2);
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_batch_touch_relocks_when_the_pool_changes__mutant() {
    // WRONG: claims the refresh of the third handle landed in domain pb.
    let c = comp();
    let pa = c.create_pool();
    let pb = c.create_pool();
    let a1 = c.track(pa, 10, sem(1)).unwrap();
    let a2 = c.track(pa, 11, sem(2)).unwrap();
    let b1 = c.track(pb, 20, sem(1)).unwrap();
    assert!(c.batch_touch(&[a1, b1, a2]) == Ok(()));
    let g = c.state.read().unwrap();
    let b = g.pools[pb as usize].lock().unwrap();
    assert!(clock_of(&b) == 3);
}

// EPSL-BATCH-TOUCH-SPANS-POOLS-ONE-LOCK-AT-A-TIME
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_batch_touch_spans_pools_one_lock_at_a_time() {
    let c = comp();
    let pa = c.create_pool();
    let pb = c.create_pool();
    let a1 = c.track(pa, 10, sem(1)).unwrap();
    let b1 = c.track(pb, 20, sem(1)).unwrap();
    let a2 = c.track(pa, 11, sem(2)).unwrap();
    // Going pa -> pb -> pa forces the component to RE-acquire pa's exclusive
    // access. `Mutex` is not reentrant, so completing at all witnesses that the
    // first guard was released before the next was taken: at no point were two
    // domain guards held together.
    assert!(c.batch_touch(&[a1, b1, a2]) == Ok(()));
    // both domains are still lockable afterwards, so no guard leaked
    let g = c.state.read().unwrap();
    assert!(g.pools[pa as usize].try_lock().is_ok());
    assert!(g.pools[pb as usize].try_lock().is_ok());
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_batch_touch_spans_pools_one_lock_at_a_time__mutant() {
    // WRONG: claims a domain guard is still held after the call returns.
    let c = comp();
    let pa = c.create_pool();
    let a1 = c.track(pa, 10, sem(1)).unwrap();
    assert!(c.batch_touch(&[a1]) == Ok(()));
    let g = c.state.read().unwrap();
    assert!(g.pools[pa as usize].try_lock().is_err());
}

// EPSL-BATCH-TOUCH-INVALID-HANDLE-IS-AN-ERROR  (divergent — refuted below)
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_batch_touch_invalid_handle_is_an_error() {
    // The spec obligation: a group holding a handle to a block that is no longer
    // tracked must report an error.
    let c = comp();
    let p = c.create_pool();
    let h1 = c.track(p, 10, sem(1)).unwrap();
    let h2 = c.track(p, 20, sem(2)).unwrap();
    assert!(c.remove(h2) == Ok(())); // h2 is now stale
    c.track(p, 30, sem(3)).unwrap(); // LIFO reuse of h2's slot
    let r = c.batch_touch(&[h1, h2]);
    kani::cover!(r == Ok(()), "the spec-forbidden success on a stale handle is reachable");
    assert!(r == Err(EvictionPolicyError::InvalidHandle));
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::stub(std::ptr::swap_nonoverlapping, swap_nonoverlapping_model)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn refute_epsl_batch_touch_invalid_handle_is_an_error() {
    // WITNESS: once the stale handle's slot has been reused the group refresh
    // silently succeeds and refreshes the block that now occupies the slot.
    let c = comp();
    let p = c.create_pool();
    let h1 = c.track(p, 10, sem(1)).unwrap();
    let h2 = c.track(p, 20, sem(2)).unwrap();
    assert!(c.remove(h2) == Ok(()));
    // while the slot is empty the group refresh correctly errors
    assert!(c.batch_touch(&[h2]) == Err(EvictionPolicyError::InvalidHandle));
    let h3 = c.track(p, 30, sem(3)).unwrap();
    assert!(h3 == h2); // same slot handed out again
    assert!(c.batch_touch(&[h1, h2]) == Ok(())); // NO error, contrary to the spec
    let g = c.state.read().unwrap();
    let pool = g.pools[p as usize].lock().unwrap();
    let i30 = ix_of(&pool, 30);
    assert!(i30 == h2.index());
    assert!(stamp_at(&pool, i30) == 5); // key 30 was refreshed instead
}

// EPSL-INV-FAILED-OPERATIONS-CHANGE-NOTHING  (divergent — refuted below)
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_inv_failed_operations_change_nothing() {
    // The spec obligation: an operation that reports an error leaves the tracking
    // state exactly as it was.
    let c = comp();
    let p = c.create_pool();
    let h1 = c.track(p, 10, sem(1)).unwrap();
    let h2 = c.track(p, 20, sem(2)).unwrap();
    let before = c.get_eviction_candidates(p, 4);
    // a group whose SECOND member is bad
    let r = c.batch_touch(&[h1, EvictionHandle::new(any_bad_pool(1), 0)]);
    assert!(r.is_err());
    let after = c.get_eviction_candidates(p, 4);
    let changed = after.len() != before.len() || (after.len() > 0 && after[0] != before[0]);
    kani::cover!(changed, "a failed operation leaving partial state behind is reachable");
    assert!(after.len() == before.len());
    for k in 0..after.len() {
        assert!(after[k] == before[k]);
    }
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::stub(std::ptr::swap_nonoverlapping, swap_nonoverlapping_model)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn refute_epsl_inv_failed_operations_change_nothing() {
    // WITNESS: `batch_touch` refreshes each handle in turn and returns at the
    // first bad one, so every earlier handle KEEPS its new recency and the
    // eviction order is permanently changed by a call the caller was told failed.
    let c = comp();
    let p = c.create_pool();
    let h1 = c.track(p, 10, sem(1)).unwrap();
    let h2 = c.track(p, 20, sem(2)).unwrap();
    assert!(c.get_eviction_candidates(p, 4)[0] == 10); // 10 is the next victim
    let r = c.batch_touch(&[h1, EvictionHandle::new(9, 0)]);
    assert!(r == Err(EvictionPolicyError::InvalidPool(9))); // reported FAILED ...
    assert!(c.get_eviction_candidates(p, 4)[0] == 20); // ... yet the order moved
    let g = c.state.read().unwrap();
    let pool = g.pools[p as usize].lock().unwrap();
    let i10 = ix_of(&pool, 10);
    assert!(stamp_at(&pool, i10) == 3); // partial effect persisted
    assert!(clock_of(&pool) == 3);
}

/// Discriminator: every SINGLE-handle operation does satisfy the invariant
/// (each validates before mutating), so the violation is isolated to
/// `batch_touch`'s mutate-as-you-go loop in `src/lib.rs:169-182`.
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::stub(std::ptr::swap_nonoverlapping, swap_nonoverlapping_model)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_inv_failed_operations_change_nothing__discriminator() {
    let c = comp();
    let p = c.create_pool();
    let h1 = c.track(p, 10, sem(1)).unwrap();
    let h2 = c.track(p, 20, sem(2)).unwrap();
    let before = c.get_eviction_candidates(p, 4);
    let bad = EvictionHandle::new(9, 0);
    assert!(c.touch(bad).is_err());
    assert!(c.remove(bad).is_err());
    assert!(c.track(9, 30, sem(3)).is_err());
    let after = c.get_eviction_candidates(p, 4);
    assert!(after.len() == before.len());
    for k in 0..after.len() {
        assert!(after[k] == before[k]);
    }
    let g = c.state.read().unwrap();
    let pool = g.pools[p as usize].lock().unwrap();
    assert!(clock_of(&pool) == 2); // no partial effect at all
}

// ===========================================================================
// read-only queries and unknown domains
// ===========================================================================

// EPSL-READONLY-QUERIES-DEGRADE-SAFELY-ON-UNKNOWN-DOMAIN
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_readonly_queries_degrade_safely_on_unknown_domain() {
    let c = comp();
    let p = c.create_pool();
    c.track(p, 10, sem(1)).unwrap();
    let bad = any_bad_pool(1);
    // the four operations that cannot report an error all degrade harmlessly
    assert!(c.identify_next_to_evict(bad).is_none());
    assert!(c.get_eviction_candidates(bad, 4).is_empty());
    assert!(c.len(bad) == 0);
    c.clear_pool(bad);
    // nothing anywhere in the component changed
    assert!(c.len(p) == 1);
    assert!(c.state.read().unwrap().pools.len() == 1);
    // and an unknown domain is indistinguishable from an empty one
    let q = c.create_pool();
    assert!(c.len(q) == c.len(bad));
    assert!(c.identify_next_to_evict(q) == c.identify_next_to_evict(bad));
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_readonly_queries_degrade_safely_on_unknown_domain__mutant() {
    // WRONG: claims an unknown domain reports a non-zero size.
    let c = comp();
    c.create_pool();
    assert!(c.len(7) > 0);
}

// EPSL-CANDIDATES-UNKNOWN-POOL-RETURNS-EMPTY
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_candidates_unknown_pool_returns_empty() {
    let c = comp();
    let p = c.create_pool();
    c.track(p, 10, sem(1)).unwrap();
    let bad = any_bad_pool(1);
    let n: usize = kani::any();
    kani::assume(n <= 8);
    let v = c.get_eviction_candidates(bad, n);
    assert!(v.is_empty());
    // indistinguishable from a live domain that has no candidates
    let q = c.create_pool();
    assert!(c.get_eviction_candidates(q, n).len() == v.len());
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_candidates_unknown_pool_returns_empty__mutant() {
    // WRONG: claims an unknown domain yields candidates.
    let c = comp();
    let p = c.create_pool();
    c.track(p, 10, sem(1)).unwrap();
    assert!(!c.get_eviction_candidates(6, 4).is_empty());
}

// EPSL-LEN-UNKNOWN-POOL-RETURNS-ZERO
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_len_unknown_pool_returns_zero() {
    let c = comp();
    let p = c.create_pool();
    c.track(p, 10, sem(1)).unwrap();
    c.track(p, 20, sem(2)).unwrap();
    let bad = any_bad_pool(1);
    assert!(c.len(bad) == 0);
    assert!(c.len(p) == 2);
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_len_unknown_pool_returns_zero__mutant() {
    // WRONG: claims the unknown domain reports the live domain's size.
    let c = comp();
    let p = c.create_pool();
    c.track(p, 10, sem(1)).unwrap();
    assert!(c.len(3) == c.len(p));
}

// EPSL-CLEAR-POOL-UNKNOWN-POOL-IS-A-SILENT-NO-OP
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_clear_pool_unknown_pool_is_a_silent_no_op() {
    let c = comp();
    let p = c.create_pool();
    let h = c.track(p, 10, sem(1)).unwrap();
    let bad = any_bad_pool(1);
    c.clear_pool(bad); // returns nothing at all — the caller cannot learn anything
    assert!(c.len(p) == 1);
    assert!(c.state.read().unwrap().pools.len() == 1);
    assert!(c.touch(h) == Ok(()));
    assert!(c.get_eviction_candidates(p, 4)[0] == 10);
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_clear_pool_unknown_pool_is_a_silent_no_op__mutant() {
    // WRONG: claims clearing an unknown domain creates it.
    let c = comp();
    c.create_pool();
    c.clear_pool(5);
    assert!(c.state.read().unwrap().pools.len() > 1);
}

// EPSL-CLEAR-POOL-LEAVES-OTHER-POOLS-ALONE
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_clear_pool_leaves_other_pools_alone() {
    let c = comp();
    let pa = c.create_pool();
    let pb = c.create_pool();
    c.track(pa, 10, sem(1)).unwrap();
    let hb = c.track(pb, 20, sem(1)).unwrap();
    c.track(pb, 21, sem(1)).unwrap();
    let (lb, clockb) = {
        let g = c.state.read().unwrap();
        let b = g.pools[pb as usize].lock().unwrap();
        (b.len(), clock_of(&b))
    };
    c.clear_pool(pa);
    assert!(c.len(pa) == 0);
    // pb is untouched: blocks, chains, recency values, counter, size, identifier
    let g = c.state.read().unwrap();
    let b = g.pools[pb as usize].lock().unwrap();
    assert!(b.len() == lb);
    assert!(clock_of(&b) == clockb);
    let i20 = ix_of(&b, 20);
    let i21 = ix_of(&b, 21);
    assert!(child_at(&b, i20) == Some(i21));
    assert!(parent_at(&b, i21) == Some(i20));
    drop(b);
    drop(g);
    assert!(c.touch(hb) == Ok(()));
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_clear_pool_leaves_other_pools_alone__mutant() {
    // WRONG: claims clearing pa also empties pb.
    let c = comp();
    let pa = c.create_pool();
    let pb = c.create_pool();
    c.track(pa, 10, sem(1)).unwrap();
    c.track(pb, 20, sem(1)).unwrap();
    c.clear_pool(pa);
    assert!(c.len(pb) == 0);
}

// EPSL-INV-DOMAINS-ARE-INDEPENDENT
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_inv_domains_are_independent() {
    let c = comp();
    let pa = c.create_pool();
    let pb = c.create_pool();
    let ha = c.track(pa, 10, sem(1)).unwrap();
    let hb = c.track(pb, 10, sem(1)).unwrap(); // SAME key, other domain
    let (lb, clockb, sb) = {
        let g = c.state.read().unwrap();
        let b = g.pools[pb as usize].lock().unwrap();
        let i = ix_of(&b, 10);
        (b.len(), clock_of(&b), stamp_at(&b, i))
    };
    // a symbolic operation on pa
    let sel: u8 = kani::any();
    kani::assume(sel < 5);
    match sel {
        0 => {
            c.track(pa, 40, sem(2)).unwrap();
        }
        1 => {
            let _ = c.touch(ha);
        }
        2 => {
            let _ = c.remove(ha);
        }
        3 => {
            let _ = c.identify_next_to_evict(pa);
        }
        _ => c.clear_pool(pa),
    }
    // pb is completely unchanged, and a victim is only chosen from pb's blocks
    let g = c.state.read().unwrap();
    let b = g.pools[pb as usize].lock().unwrap();
    let i = ix_of(&b, 10);
    assert!(b.len() == lb);
    assert!(clock_of(&b) == clockb);
    assert!(stamp_at(&b, i) == sb);
    drop(b);
    drop(g);
    assert!(c.len(pb) == lb);
    assert!(c.identify_next_to_evict(pb) == Some(10));
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_inv_domains_are_independent__mutant() {
    // WRONG: claims a registration in pa is visible in pb.
    let c = comp();
    let pa = c.create_pool();
    let pb = c.create_pool();
    c.track(pa, 10, sem(1)).unwrap();
    assert!(c.len(pb) == 1);
}

// EPSL-INV-POOL-IDS-STAY-VALID-FOREVER
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_inv_pool_ids_stay_valid_forever() {
    let c = comp();
    let pa = c.create_pool();
    let h = c.track(pa, 10, sem(1)).unwrap();
    let n0 = c.state.read().unwrap().pools.len();
    // there is no operation that destroys a domain, so the vector only grows and
    // an identifier never becomes stale or gets recycled
    c.clear_pool(pa);
    let _ = c.remove(h);
    let _ = c.identify_next_to_evict(pa);
    assert!(c.state.read().unwrap().pools.len() == n0);
    let pb = c.create_pool();
    assert!(pb != pa);
    assert!(c.state.read().unwrap().pools.len() == n0 + 1);
    // pa still names a usable domain
    let h2 = c.track(pa, 50, sem(3)).unwrap();
    assert!(h2.pool_id() == pa);
    assert!(c.len(pa) == 1);
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_inv_pool_ids_stay_valid_forever__mutant() {
    // WRONG: claims clearing a domain destroys it, so its identifier is reused.
    let c = comp();
    let pa = c.create_pool();
    c.clear_pool(pa);
    let pb = c.create_pool();
    assert!(pb == pa);
}

// EPSL-NO-INPUT-CAN-MAKE-AN-OPERATION-PANIC
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_no_input_can_make_an_operation_panic() {
    // Any domain identifier, any handle, any requested count: every operation
    // either succeeds or reports an error. Kani checks reachable panics/aborts
    // (including the arithmetic and bounds checks inside the arena) for free, so a
    // passing run IS the totality proof over this input geometry.
    let c = comp();
    let p = c.create_pool();
    c.track(p, 10, sem(1)).unwrap();
    let pool: PoolId = kani::any();
    let ix: u32 = kani::any();
    let n: usize = kani::any();
    let s: u64 = kani::any();
    let h = EvictionHandle::new(pool, ix);
    let _ = c.track(pool, 10, sem(s));
    let _ = c.touch(h);
    let _ = c.batch_touch(&[h]);
    let _ = c.remove(h);
    let _ = c.identify_next_to_evict(pool);
    let _ = c.get_eviction_candidates(pool, n);
    let _ = c.len(pool);
    c.clear_pool(pool);
    let _ = c.create_pool();
}

/// `concrete_inputs` lever variant: concrete representative inputs instead of a
/// fully symbolic handle/count, in case the symbolic form blows up the solver.
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_no_input_can_make_an_operation_panic__concrete() {
    let c = comp();
    let p = c.create_pool();
    c.track(p, 10, sem(1)).unwrap();
    let h = EvictionHandle::new(9, 7); // unknown domain, out-of-range slot
    let _ = c.track(9, 10, sem(0));
    let _ = c.touch(h);
    let _ = c.batch_touch(&[h]);
    let _ = c.remove(h);
    let _ = c.identify_next_to_evict(9);
    let _ = c.get_eviction_candidates(9, usize::MAX);
    let _ = c.len(9);
    c.clear_pool(9);
    // and the same against the LIVE domain with an out-of-range slot
    let g = EvictionHandle::new(p, 7);
    let _ = c.touch(g);
    let _ = c.remove(g);
    let _ = c.get_eviction_candidates(p, usize::MAX);
}

/// `split_harness` lever variant: the handle-taking half only.
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_no_input_can_make_an_operation_panic__split_handles() {
    let c = comp();
    let p = c.create_pool();
    c.track(p, 10, sem(1)).unwrap();
    let pool: PoolId = kani::any();
    let ix: u32 = kani::any();
    let h = EvictionHandle::new(pool, ix);
    let _ = c.touch(h);
    let _ = c.remove(h);
    let _ = c.batch_touch(&[h]);
}

/// `split_harness` lever variant: the query half only.
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_no_input_can_make_an_operation_panic__split_queries() {
    let c = comp();
    let p = c.create_pool();
    c.track(p, 10, sem(1)).unwrap();
    let pool: PoolId = kani::any();
    let n: usize = kani::any();
    let _ = c.identify_next_to_evict(pool);
    let _ = c.get_eviction_candidates(pool, n);
    let _ = c.len(pool);
    c.clear_pool(pool);
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_no_input_can_make_an_operation_panic__mutant() {
    // WRONG: claims an out-of-range handle is accepted, i.e. the operation is
    // NOT total-with-an-error but total-with-a-success.
    let c = comp();
    let p = c.create_pool();
    c.track(p, 10, sem(1)).unwrap();
    assert!(c.touch(EvictionHandle::new(p, 7)).is_ok());
}

// EPSL-LOCKS-ASSUMED-NEVER-POISONED
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_locks_assumed_never_poisoned() {
    // Every operation does `.unwrap()` on its lock result. Under the documented
    // assumption (no earlier operation panicked while holding a lock) every
    // acquisition is `Ok`, so no operation aborts on a lock. This harness drives
    // all nine operations and would abort on the first poisoned-lock unwrap.
    let c = comp();
    let p = c.create_pool();
    assert!(c.state.read().unwrap().pools[p as usize].lock().is_ok());
    let h = c.track(p, 10, sem(1)).unwrap();
    assert!(c.touch(h) == Ok(()));
    assert!(c.batch_touch(&[h]) == Ok(()));
    assert!(c.len(p) == 1);
    assert!(c.get_eviction_candidates(p, 4).len() == 1);
    assert!(c.identify_next_to_evict(p) == Some(10));
    c.clear_pool(p);
    let h2 = c.track(p, 20, sem(2)).unwrap();
    assert!(c.remove(h2) == Ok(()));
    // the write lock is also acquirable after every read-lock operation
    assert!(c.state.write().is_ok());
    assert!(c.state.read().is_ok());
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_locks_assumed_never_poisoned__mutant() {
    // WRONG: claims a lock acquisition fails on an unpoisoned lock.
    let c = comp();
    let p = c.create_pool();
    assert!(c.state.read().is_err());
}

// EPSL-ONLY-POOL-CREATION-TAKES-THE-EXCLUSIVE-LOCK
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_only_pool_creation_takes_the_exclusive_lock() {
    let c = comp();
    let p = c.create_pool();
    let h = c.track(p, 10, sem(1)).unwrap();
    // create_pool is the only operation that needs EXCLUSIVE access to the shared
    // state: while a shared (read) guard is held, every other operation still
    // completes, which is only possible because each takes shared access too.
    let guard = c.state.read().unwrap();
    assert!(guard.pools.len() == 1);
    drop(guard);
    let g2 = c.state.read().unwrap();
    let g3 = c.state.read().unwrap(); // shared access is shareable
    assert!(g2.pools.len() == g3.pools.len());
    drop(g2);
    drop(g3);
    // and each non-creating operation takes exclusive access only to the ONE
    // domain it works on, so the other domain stays lockable throughout
    let q = c.create_pool();
    let g = c.state.read().unwrap();
    let held = g.pools[p as usize].lock().unwrap();
    assert!(g.pools[q as usize].try_lock().is_ok());
    drop(held);
    drop(g);
    assert!(c.touch(h) == Ok(()));
}

#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_only_pool_creation_takes_the_exclusive_lock__mutant() {
    // WRONG: claims shared access to the component state is exclusive, so a
    // second reader would be refused.
    let c = comp();
    c.create_pool();
    let g2 = c.state.read().unwrap();
    assert!(c.state.try_read().is_err());
}

// ===========================================================================
// Lever variants for the two announce obligations. MEASURED: with a logger
// connected, `create_pool` calls `logger.debug(&format!("...pool {id}"))`, and a
// `format!` has no natural ceiling for CBMC — both base harnesses exceed 200 s.
// These are the `concrete_inputs` and `split_harness` levers the sat-timeout
// class requires, so the gate can adjudicate instead of returning UNRESOLVED.
// ===========================================================================

/// `concrete_inputs` lever: the smallest logger-attached scenario — ONE
/// `create_pool`, so exactly one `format!` is in the path.
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_create_pool_announces_at_most_once__concrete() {
    let c = comp();
    let lg = Arc::new(CountingLogger {
        infos: AtomicUsize::new(0),
    });
    let dynlg: Arc<dyn ILogger + Send + Sync> = lg.clone();
    assert!(c.logger.connect(dynlg).is_ok());
    c.create_pool();
    assert!(lg.infos.load(Ordering::SeqCst) == 1);
    assert!(c.state.read().unwrap().announced);
}

/// `split_harness` lever, half 1: the latch GATES the announcement. With no
/// logger in the path there is no `format!`, so this closes cheaply and proves
/// the half that does not need one.
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_create_pool_announces_at_most_once__split_latch() {
    let c = comp();
    c.create_pool();
    c.create_pool();
    c.create_pool();
    // the announcement was never made, so the latch was never consumed
    assert!(!c.state.read().unwrap().announced);
}

/// `split_harness` lever, half 2: a faithful mirror of the exact gate at
/// `src/lib.rs:110-117` (`if !announced { announce; announced = true }`) over a
/// SYMBOLIC initial latch and a symbolic number of domain creations: the number
/// of announcements is at most one. Fidelity: arithmetic-core (the gate's control
/// flow, extracted; the real-code half is the `__concrete` variant above).
#[kani::proof]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_create_pool_announces_at_most_once__split_gate() {
    let mut announced: bool = kani::any();
    let start = announced;
    let n: u8 = kani::any();
    kani::assume(n <= 4);
    let mut announcements = 0u8;
    let mut i = 0u8;
    while i < n {
        if !announced {
            announcements += 1;
            announced = true;
        }
        i += 1;
    }
    assert!(announcements <= 1);
    if start {
        assert!(announcements == 0);
    }
    assert!(announced == (start || n > 0));
}

/// `concrete_inputs` lever: one domain created with no logger, then a logger is
/// connected and one more domain created — the minimal witness that a pre-logger
/// domain does not consume the announcement.
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_announce_latch_set_only_with_a_logger__concrete() {
    let c = comp();
    c.create_pool();
    assert!(!c.state.read().unwrap().announced);
}

/// `split_harness` lever: the no-logger half, over several domains, with no
/// `format!` anywhere in the path.
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_announce_latch_set_only_with_a_logger__split_nologger() {
    let c = comp();
    c.create_pool();
    c.create_pool();
    c.create_pool();
    assert!(!c.state.read().unwrap().announced);
    assert!(c.state.read().unwrap().pools.len() == 3);
}

// ===========================================================================
// Lever variants for the three multi-domain / all-operation harnesses that
// exceed 200 s even with loops cut (MEASURED). These are the `concrete_inputs`
// and `split_harness` levers the sat-timeout class requires.
// ===========================================================================

/// `split_harness`: the shared-access half — two simultaneous read guards on the
/// component state, so non-creating operations take SHARED access.
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_only_pool_creation_takes_the_exclusive_lock__split_shared() {
    let c = comp();
    c.create_pool();
    let g2 = c.state.read().unwrap();
    let g3 = c.state.read().unwrap();
    assert!(g2.pools.len() == g3.pools.len());
    assert!(g2.pools.len() == 1);
}

/// `split_harness`: the per-domain half — holding one domain's exclusive guard
/// leaves the other domain lockable, so a non-creating operation locks only the
/// domain it works on.
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_only_pool_creation_takes_the_exclusive_lock__split_perdomain() {
    let c = comp();
    let p = c.create_pool();
    let q = c.create_pool();
    let g = c.state.read().unwrap();
    let held = g.pools[p as usize].lock().unwrap();
    assert!(g.pools[q as usize].try_lock().is_ok());
}

/// `concrete_inputs`: the minimal witness — one domain, a shared guard taken and
/// released, then a creating operation taking the exclusive guard.
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_only_pool_creation_takes_the_exclusive_lock__concrete() {
    let c = comp();
    let g = c.state.read().unwrap();
    assert!(g.pools.is_empty());
    drop(g);
    let p = c.create_pool();
    assert!(p == 0);
}

/// `split_harness`: the read-side half of lock totality — the four operations
/// that take only a shared state guard plus one domain guard.
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_locks_assumed_never_poisoned__split_queries() {
    let c = comp();
    let p = c.create_pool();
    assert!(c.len(p) == 0);
    assert!(c.get_eviction_candidates(p, 4).is_empty());
    assert!(c.identify_next_to_evict(p).is_none());
    c.clear_pool(p);
    assert!(c.state.read().is_ok());
    assert!(c.state.write().is_ok());
}

/// `concrete_inputs`: the minimal witness — every lock acquisition on the path of
/// a single registration is `Ok`, so nothing aborts on a lock.
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_locks_assumed_never_poisoned__concrete() {
    let c = comp();
    let p = c.create_pool();
    assert!(c.state.read().unwrap().pools[p as usize].lock().is_ok());
    let h = c.track(p, 10, sem(1)).unwrap();
    assert!(c.touch(h) == Ok(()));
}

/// `split_harness`: the re-lock half — after a group refresh returns, the domain
/// Mutex is free again, so no guard was retained.
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_batch_touch_spans_pools_one_lock_at_a_time__split_released() {
    let c = comp();
    let pa = c.create_pool();
    let a1 = c.track(pa, 10, sem(1)).unwrap();
    assert!(c.batch_touch(&[a1]) == Ok(()));
    let g = c.state.read().unwrap();
    assert!(g.pools[pa as usize].try_lock().is_ok());
}

/// `concrete_inputs`: the minimal cross-domain group — one handle per domain, so
/// exactly one domain switch happens.
#[kani::proof]
#[kani::stub(RandomState::new, concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epsl_batch_touch_spans_pools_one_lock_at_a_time__concrete() {
    let c = comp();
    let pa = c.create_pool();
    let pb = c.create_pool();
    let a1 = c.track(pa, 10, sem(1)).unwrap();
    let b1 = c.track(pb, 20, sem(1)).unwrap();
    assert!(c.batch_touch(&[a1, b1]) == Ok(()));
    let g = c.state.read().unwrap();
    assert!(g.pools[pa as usize].try_lock().is_ok());
    assert!(g.pools[pb as usize].try_lock().is_ok());
}
