// GENERATED by ../gen_component_mutants.py — do not edit by hand; regenerate instead.
//
// Anti-vacuity twins for the real-component harnesses in proofs_component.rs. Each
// `verify_<id>__mutant` is its base harness verbatim with ONE assertion negated (see the
// generator's docstring). The gate requires every twin to FAIL under the same flags the
// base proved with (`--unwind 4 --no-unwinding-checks`, and `--unwind 8` if escalated).

use crate::api::*;

const A: CacheKey = 10;
const B: CacheKey = 20;
const C: CacheKey = 30;
const D: CacheKey = 40;

/// Twin of `verify_epo_create_pool_pre_total` (EPO-CREATE-POOL-PRE-TOTAL): negates `p0 != p1 && p1 != p2 && p0 != p2`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_create_pool_pre_total__mutant() {
    let c = component();

    // ... from the initial state.
    let p0 = c.create_pool();
    assert!(c.len(p0) == 0);

    // ... from a state that holds an entry.
    let _h = track_ok(&c, p0, A);
    let p1 = c.create_pool();
    assert!(c.len(p1) == 0);

    // ... and from a state whose pool has just been emptied.
    c.clear_pool(p0);
    let p2 = c.create_pool();
    assert!(c.len(p2) == 0);

    assert!(!(p0 != p1 && p1 != p2 && p0 != p2)); // MUTANT: negated
}

/// Twin of `verify_epo_create_pool_post_fresh_state` (EPO-CREATE-POOL-POST-FRESH-STATE): negates `keys_eq(&c.get_eviction_candidates(p, 2), &[B, A])`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_create_pool_post_fresh_state__mutant() {
    let c = component();
    let p = c.create_pool();

    assert!(c.len(p) == 0);
    let n: usize = kani::any();
    kani::assume(n <= 4);
    assert!(c.get_eviction_candidates(p, n).len() == 0);
    assert!(c.identify_next_to_evict(p).is_none());

    let h1 = track_ok(&c, p, A);
    assert!(c.len(p) == 1);
    let h2 = track_ok(&c, p, B);
    assert!(c.len(p) == 2);
    assert!(h1.index() != h2.index());
    assert!(!(keys_eq(&c.get_eviction_candidates(p, 2), &[B, A]))); // MUTANT: negated
}

/// Twin of `verify_epo_create_pool_frame_existing_pools` (EPO-CREATE-POOL-FRAME-EXISTING-POOLS): negates `c.len(b) == 0`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_create_pool_frame_existing_pools__mutant() {
    let c = component();
    let a = c.create_pool();
    let _h1 = track_ok(&c, a, A);
    let _h2 = track_ok(&c, a, B);
    let before = c.get_eviction_candidates(a, 4);
    assert!(keys_eq(&before, &[B, A]));

    let b = c.create_pool();

    // `a` still names the same pool, with the same entries in the same eviction order.
    assert!(b != a);
    assert!(c.len(a) == 2);
    assert!(keys_eq(&c.get_eviction_candidates(a, 4), &before));
    // and the new pool is a separate, empty one.
    assert!(!(c.len(b) == 0)); // MUTANT: negated
}

/// Twin of `verify_epo_track_pre_pool_exists` (EPO-TRACK-PRE-POOL-EXISTS): negates `is_invalid_pool(&r, bad)`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_track_pre_pool_exists__mutant() {
    let c = component();
    let p = c.create_pool();

    let key: CacheKey = kani::any();
    let session: u64 = kani::any();
    let h = track_ok_sem(&c, p, key, BlockSemantics { session_id: session });
    assert!(h.pool_id() == p);
    assert!(c.len(p) == 1);

    // Only pool 0 exists, so every other identifier is one that was never handed out.
    let bad: PoolId = kani::any();
    kani::assume(bad != p);
    let r = c.track(bad, key, BlockSemantics { session_id: session });
    assert!(!(is_invalid_pool(&r, bad))); // MUTANT: negated
}

/// Twin of `verify_epo_track_post_handle` (EPO-TRACK-POST-HANDLE): negates `keys_eq(&c.get_eviction_candidates(p, 4), &[B])`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_track_post_handle__mutant() {
    let c = component();
    let p = c.create_pool();

    let h1 = track_ok(&c, p, A);
    let h2 = track_ok(&c, p, B);
    assert!(h1.pool_id() == p && h2.pool_id() == p);
    assert!(h1.index() != h2.index());
    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &[B, A]));

    remove_ok(&c, h1);
    assert!(c.len(p) == 1);
    assert!(!(keys_eq(&c.get_eviction_candidates(p, 4), &[B]))); // MUTANT: negated
}

/// Twin of `verify_epo_track_post_len_increment` (EPO-TRACK-POST-LEN-INCREMENT): negates `c.len(p) == 2`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_track_post_len_increment__mutant() {
    let c = component();
    let p = c.create_pool();

    let k1: CacheKey = kani::any();
    let k2: CacheKey = kani::any();

    assert!(c.len(p) == 0);
    let _h1 = track_ok(&c, p, k1);
    assert!(c.len(p) == 1);
    let _h2 = track_ok(&c, p, k2);
    assert!(!(c.len(p) == 2)); // MUTANT: negated
}

/// Twin of `verify_epo_track_post_access_count` (EPO-TRACK-POST-ACCESS-COUNT): negates `c.len(p) == 0`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_track_post_access_count__mutant() {
    // --- the update, mirrored from lib.rs:123 over a symbolic starting value ---
    let ac: u64 = kani::any();
    // A pool's tally is raised once per track and a track allocates a `Node`, so the tally
    // is bounded by the number of allocations a process can make; 2^48 is far above that
    // and far below u64::MAX.
    kani::assume(ac < (1u64 << 48));
    let ac_after = ac + 1; // lib.rs:123
    assert!(ac_after == ac + 1);
    assert!(ac_after > ac);

    // --- the observable half, against the real component ---
    let c = component();
    let p = c.create_pool();
    let h1 = track_ok(&c, p, A);
    let h2 = track_ok(&c, p, B);
    let order = c.get_eviction_candidates(p, 4);
    assert!(keys_eq(&order, &[B, A]));

    // None of these is a track, and none of them changes membership or the tally's
    // consequences: the eviction order after a touch is the touch's own effect and nothing
    // else, and `len`/`get_eviction_candidates` change nothing at all.
    touch_ok(&c, h2);
    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &[A, B]));
    batch_ok(&c, &[h1]);
    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &[B, A]));
    assert!(c.len(p) == 2);
    remove_ok(&c, h1);
    assert!(c.len(p) == 1);
    c.clear_pool(p);
    assert!(!(c.len(p) == 0)); // MUTANT: negated
}

/// Twin of `verify_epo_track_inv_aging_no_division_by_zero` (EPO-TRACK-INV-AGING-NO-DIVISION-BY-ZERO): negates `c.len(p) == 3`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_track_inv_aging_no_division_by_zero__mutant() {
    let c = component();
    let p = c.create_pool();

    let k1: CacheKey = kani::any();

    // max_len is 0 here: the remainder must not be evaluated at all.
    let _h1 = track_ok(&c, p, k1);
    // max_len becomes 1 here, and 2 on the next: the remainder IS evaluated, with a
    // divisor the guard has proved non-zero.
    let _h2 = track_ok(&c, p, B);
    let _h3 = track_ok(&c, p, C);
    assert!(!(c.len(p) == 3)); // MUTANT: negated
}

/// Twin of `verify_epo_track_post_admit_empty_pool` (EPO-TRACK-POST-ADMIT-EMPTY-POOL): negates `c.len(p) == 0`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_track_post_admit_empty_pool__mutant() {
    let c = component();
    let p = c.create_pool();

    // A first-time key into an empty pool.
    let h1 = track_ok(&c, p, A);
    assert!(c.len(p) == 1);
    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &[A]));

    // Empty it again, leaving A's estimate at 1 — the estimator is not reset by removal.
    remove_ok(&c, h1);
    assert!(c.len(p) == 0);

    // A key the estimator has already seen, into an empty pool: same branch.
    let _h2 = track_ok(&c, p, A);
    assert!(c.len(p) == 1);
    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &[A]));
    // It is the front (the next victim) and the back (the protected end) at once.
    assert!(c.identify_next_to_evict(p) == Some(A));
    assert!(!(c.len(p) == 0)); // MUTANT: negated
}

/// Twin of `verify_epo_track_post_admit_more_frequent` (EPO-TRACK-POST-ADMIT-MORE-FREQUENT): negates `c.identify_next_to_evict(p) == Some(B)`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_track_post_admit_more_frequent__mutant() {
    let c = component();
    let p = c.create_pool();

    let h_a = track_ok(&c, p, A); // estimate(A) = 1, list [A]
    let _h_b = track_ok(&c, p, B); // estimate(B) = 1, list [B, A]
    remove_ok(&c, h_a); // list [B]; estimate(A) still 1
    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &[B]));

    let _h_a2 = track_ok(&c, p, A); // estimate(A) = 2 > estimate(B) = 1 -> push_back

    assert!(c.len(p) == 2);
    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &[B, A]));
    // The protected end is the one that is NOT evicted next.
    assert!(!(c.identify_next_to_evict(p) == Some(B))); // MUTANT: negated
}

/// Twin of `verify_epo_track_post_admit_not_more_frequent` (EPO-TRACK-POST-ADMIT-NOT-MORE-FREQUENT): negates `c.identify_next_to_evict(p) == Some(C)`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_track_post_admit_not_more_frequent__mutant() {
    let c = component();
    let p = c.create_pool();

    let _h_a = track_ok(&c, p, A); // list [A], estimate(A) = 1
    let _h_b = track_ok(&c, p, B); // tie 1 <= 1 -> push_front, list [B, A]

    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &[B, A]));
    assert!(c.identify_next_to_evict(p) == Some(B)); // B is the very next victim

    // ... and again from the resulting state: C ties with the new head A.
    let _h_c = track_ok(&c, p, C);
    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &[C, A]));
    assert!(!(c.identify_next_to_evict(p) == Some(C))); // MUTANT: negated
}

/// Twin of `verify_epo_track_frame_semantics_ignored` (EPO-TRACK-FRAME-SEMANTICS-IGNORED): negates `keys_eq(&c.get_eviction_candidates(p, 4), &[B, A])`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_track_frame_semantics_ignored__mutant() {
    let c = component();
    let p = c.create_pool();

    let s1: u64 = kani::any();
    let s2: u64 = kani::any();

    let h1 = track_ok_sem(&c, p, A, BlockSemantics { session_id: s1 });
    let h2 = track_ok_sem(&c, p, B, BlockSemantics { session_id: s2 });

    // Exactly the hint-blind outcome, for every pair of hint values.
    assert!(h1.pool_id() == p && h2.pool_id() == p);
    assert!(h1.index() == 0 && h2.index() == 1);
    assert!(c.len(p) == 2);
    assert!(!(keys_eq(&c.get_eviction_candidates(p, 4), &[B, A]))); // MUTANT: negated
}

/// Twin of `verify_epo_track_frame_other_pools` (EPO-TRACK-FRAME-OTHER-POOLS): negates `c.len(b) == 1`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_track_frame_other_pools__mutant() {
    let c = component();
    let a = c.create_pool();
    let b = c.create_pool();

    let _h1 = track_ok(&c, a, A);
    let _h2 = track_ok(&c, a, B);
    let a_before = c.get_eviction_candidates(a, 4);
    assert!(keys_eq(&a_before, &[B, A]));

    let _h3 = track_ok(&c, b, C);

    assert!(c.len(a) == 2);
    assert!(keys_eq(&c.get_eviction_candidates(a, 4), &a_before));
    assert!(!(c.len(b) == 1)); // MUTANT: negated
}

/// Twin of `verify_epo_track_error_invalid_pool` (EPO-TRACK-ERROR-INVALID-POOL): negates `is_invalid_pool(&r, bad)`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_track_error_invalid_pool__mutant() {
    let c = component();
    let p = c.create_pool();
    assert!(p == 0);

    let bad: PoolId = kani::any();
    kani::assume(bad != p);
    let key: CacheKey = kani::any();

    let r = c.track(bad, key, sem());
    assert!(r.is_err());
    assert!(!(is_invalid_pool(&r, bad))); // MUTANT: negated
}

/// Twin of `verify_epo_track_error_frame_no_mutation` (EPO-TRACK-ERROR-FRAME-NO-MUTATION): negates `keys_eq(&c.get_eviction_candidates(p, 4), &[C, B, A])`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_track_error_frame_no_mutation__mutant() {
    let c = component();
    let p = c.create_pool();
    let _h1 = track_ok(&c, p, A);
    let _h2 = track_ok(&c, p, B);
    let before = c.get_eviction_candidates(p, 4);
    assert!(keys_eq(&before, &[B, A]));

    let bad: PoolId = kani::any();
    kani::assume(bad != p);
    let r = c.track(bad, C, sem());
    assert!(is_invalid_pool(&r, bad));

    // Nothing moved in the pool that does exist ...
    assert!(c.len(p) == 2);
    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &before));
    // ... no pool was created ...
    assert!(c.len(1) == 0);
    assert!(c.identify_next_to_evict(1).is_none());
    // ... and C's estimate was not raised: tracked now, it ties with head B (both 1) and
    // is admitted at the eviction end, the first-timer outcome. Had the failed call
    // incremented C, it would have landed at the protected end instead.
    let _h3 = track_ok(&c, p, C);
    assert!(!(keys_eq(&c.get_eviction_candidates(p, 4), &[C, B, A]))); // MUTANT: negated
}

/// Twin of `verify_epo_touch_pre_pool_exists` (EPO-TOUCH-PRE-POOL-EXISTS): negates `is_invalid_pool(&r, bad)`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_touch_pre_pool_exists__mutant() {
    let c = component();
    let p = c.create_pool();

    let _h1 = track_ok(&c, p, A);
    let h2 = track_ok(&c, p, B); // list [B, A]
    touch_ok(&c, h2); // B to the protected end
    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &[A, B]));

    let bad: PoolId = kani::any();
    kani::assume(bad != p);
    let r = c.touch(EvictionHandle::new(bad, 0));
    assert!(!(is_invalid_pool(&r, bad))); // MUTANT: negated
}

/// Twin of `verify_epo_touch_frame_sketch_unchanged` (EPO-TOUCH-FRAME-SKETCH-UNCHANGED): negates `keys_eq(&c.get_eviction_candidates(p, 4), &[B, C, A])`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_touch_frame_sketch_unchanged__mutant() {
    let c = component();
    let p = c.create_pool();

    // Give A an estimate of 1 without leaving it in the pool.
    let h_a = track_ok(&c, p, A);
    remove_ok(&c, h_a);

    let _h_b = track_ok(&c, p, B); // list [B],     estimate(B) = 1
    let h_cc = track_ok(&c, p, C); // tie -> list [C, B], estimate(C) = 1

    // The operation under test: a real move, not the no-op early return.
    touch_ok(&c, h_cc);
    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &[B, C]));

    // PROBE: estimate(A) becomes 2, head B's is 1, so A must go to the protected end.
    let _h_a2 = track_ok(&c, p, A);
    assert!(!(keys_eq(&c.get_eviction_candidates(p, 4), &[B, C, A]))); // MUTANT: negated
}

/// Twin of `verify_epo_touch_frame_counters` (EPO-TOUCH-FRAME-COUNTERS): negates `keys_eq(&c.get_eviction_candidates(p, 4), &[C, B, A])`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_touch_frame_counters__mutant() {
    let c = component();
    let p = c.create_pool();

    let h_a = track_ok(&c, p, A);
    let h_b = track_ok(&c, p, B); // list [B, A]
    assert!(c.len(p) == 2);

    touch_ok(&c, h_b);
    assert!(c.len(p) == 2); // nothing added, nothing dropped
    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &[A, B]));

    touch_ok(&c, h_a);
    assert!(c.len(p) == 2);
    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &[B, A]));

    // Touching repeatedly is still only a reordering: the pool is exactly two entries, and
    // a subsequent track still behaves as a first-timer's tie against the head.
    let _h_c = track_ok(&c, p, C);
    assert!(c.len(p) == 3);
    assert!(!(keys_eq(&c.get_eviction_candidates(p, 4), &[C, B, A]))); // MUTANT: negated
}

/// Twin of `verify_epo_touch_error_invalid_pool` (EPO-TOUCH-ERROR-INVALID-POOL): negates `keys_eq(&c.get_eviction_candidates(p, 4), &before)`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_touch_error_invalid_pool__mutant() {
    let c = component();
    let p = c.create_pool();
    let _h1 = track_ok(&c, p, A);
    let _h2 = track_ok(&c, p, B);
    let before = c.get_eviction_candidates(p, 4);

    let bad: PoolId = kani::any();
    kani::assume(bad != p);
    let idx: u32 = kani::any(); // the slot field is irrelevant: the pool check runs first

    let r = c.touch(EvictionHandle::new(bad, idx));
    assert!(r.is_err());
    assert!(is_invalid_pool(&r, bad));

    assert!(c.len(p) == 2);
    assert!(!(keys_eq(&c.get_eviction_candidates(p, 4), &before))); // MUTANT: negated
}

/// Twin of `verify_epo_batch_touch_pre_pools_exist` (EPO-BATCH-TOUCH-PRE-POOLS-EXIST): negates `is_invalid_pool(&r, bad)`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_batch_touch_pre_pools_exist__mutant() {
    let c = component();
    let a = c.create_pool();
    let b = c.create_pool();

    let ha = track_ok(&c, a, A);
    let hb = track_ok(&c, b, B);

    // Mixed pools, and the same handles in the other order.
    batch_ok(&c, &[ha, hb]);
    batch_ok(&c, &[hb, ha]);
    // The same pool twice with another in between — the alternating case.
    batch_ok(&c, &[ha, hb, ha]);
    // An empty batch is always allowed.
    batch_ok(&c, &[]);

    assert!(c.len(a) == 1 && c.len(b) == 1);

    // ... and a handle naming a pool that was never created is rejected.
    let bad: PoolId = kani::any();
    kani::assume(bad != a && bad != b);
    let r = c.batch_touch(&[EvictionHandle::new(bad, 0)]);
    assert!(!(is_invalid_pool(&r, bad))); // MUTANT: negated
}

/// Twin of `verify_epo_batch_touch_post_empty_noop` (EPO-BATCH-TOUCH-POST-EMPTY-NOOP): negates `keys_eq(&c.get_eviction_candidates(p, 4), &before)`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_batch_touch_post_empty_noop__mutant() {
    let c = component();

    // A component with NO pools accepts the empty batch.
    assert!(c.batch_touch(&[]).is_ok());

    let p = c.create_pool();
    let _h1 = track_ok(&c, p, A);
    let _h2 = track_ok(&c, p, B);
    let before = c.get_eviction_candidates(p, 4);
    assert!(keys_eq(&before, &[B, A]));

    assert!(c.batch_touch(&[]).is_ok());

    assert!(c.len(p) == 2);
    assert!(!(keys_eq(&c.get_eviction_candidates(p, 4), &before))); // MUTANT: negated
}

/// Twin of `verify_epo_batch_touch_post_equivalent_to_sequential` (EPO-BATCH-TOUCH-POST-EQUIVALENT-TO-SEQUENTIAL): negates `keys_eq(&after_a, &[B, C, A])`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_batch_touch_post_equivalent_to_sequential__mutant() {
    let c = component();
    let a = c.create_pool();
    let b = c.create_pool();

    let ha1 = track_ok(&c, a, A);
    let _ha2 = track_ok(&c, a, B);
    let ha3 = track_ok(&c, a, C);

    let hb1 = track_ok(&c, b, A);
    let _hb2 = track_ok(&c, b, B);
    let hb3 = track_ok(&c, b, C);

    // Identical starting states.
    let start = c.get_eviction_candidates(a, 4);
    assert!(keys_eq(&start, &[C, B, A]));
    assert!(keys_eq(&c.get_eviction_candidates(b, 4), &start));

    // One batch ...
    batch_ok(&c, &[ha3, ha1]);
    // ... versus the same two touches applied one at a time, in the same order.
    touch_ok(&c, hb3);
    touch_ok(&c, hb1);

    let after_a = c.get_eviction_candidates(a, 4);
    let after_b = c.get_eviction_candidates(b, 4);
    assert!(keys_eq(&after_a, &after_b));
    assert!(c.len(a) == c.len(b));
    // The LAST handle naming the pool is now its most protected entry.
    assert!(!(keys_eq(&after_a, &[B, C, A]))); // MUTANT: negated
}

/// Twin of `verify_epo_batch_touch_frame_membership_and_sketch` (EPO-BATCH-TOUCH-FRAME-MEMBERSHIP-AND-SKETCH): negates `keys_eq(&c.get_eviction_candidates(a, 4), &[B, C, A, A])`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_batch_touch_frame_membership_and_sketch__mutant() {
    let c = component();
    let a = c.create_pool();
    let b = c.create_pool();

    let ha1 = track_ok(&c, a, A);
    let _ha2 = track_ok(&c, a, B);
    let ha3 = track_ok(&c, a, C); // a: [C, B, A]
    let _hb = track_ok(&c, b, D); // b: [D]

    assert!(keys_eq(&c.get_eviction_candidates(a, 4), &[C, B, A]));

    batch_ok(&c, &[ha3, ha1]);

    // Exactly a reordering of the same three keys.
    assert!(c.len(a) == 3);
    assert!(keys_eq(&c.get_eviction_candidates(a, 4), &[B, C, A]));
    // The pool no handle named is untouched.
    assert!(c.len(b) == 1);
    assert!(keys_eq(&c.get_eviction_candidates(b, 4), &[D]));

    // PROBE: head B's estimate is still 1, so re-tracking A (estimate 2) must go to the
    // protected end. A batch that had incremented B would tie and put A at the front.
    let _ha4 = track_ok(&c, a, A);
    assert!(!(keys_eq(&c.get_eviction_candidates(a, 4), &[B, C, A, A]))); // MUTANT: negated
}

/// Twin of `verify_epo_batch_touch_error_invalid_pool` (EPO-BATCH-TOUCH-ERROR-INVALID-POOL): negates `is_invalid_pool(&r_later, bad)`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_batch_touch_error_invalid_pool__mutant() {
    let c = component();
    let a = c.create_pool();
    let ha = track_ok(&c, a, A);

    let bad: PoolId = kani::any();
    kani::assume(bad != a);
    let bh = EvictionHandle::new(bad, 0);

    let r_first = c.batch_touch(&[bh, ha]);
    assert!(is_invalid_pool(&r_first, bad));

    let r_later = c.batch_touch(&[ha, bh]);
    assert!(!(is_invalid_pool(&r_later, bad))); // MUTANT: negated
}

/// Twin of `verify_epo_batch_touch_error_partial_application` (EPO-BATCH-TOUCH-ERROR-PARTIAL-APPLICATION): negates `keys_eq(&c.get_eviction_candidates(a, 4), &[B, A, C])`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_batch_touch_error_partial_application__mutant() {
    let c = component();
    let a = c.create_pool();

    let h1 = track_ok(&c, a, A);
    let _h2 = track_ok(&c, a, B);
    let h3 = track_ok(&c, a, C); // [C, B, A]

    let bad: PoolId = kani::any();
    kani::assume(bad != a);

    let r = c.batch_touch(&[h3, EvictionHandle::new(bad, 0), h1]);
    assert!(is_invalid_pool(&r, bad));

    // C's access took effect (it moved to the back); A's did not (it did not move).
    assert!(c.len(a) == 3);
    assert!(!(keys_eq(&c.get_eviction_candidates(a, 4), &[B, A, C]))); // MUTANT: negated
}

/// Twin of `verify_epo_batch_touch_error_no_log` (EPO-BATCH-TOUCH-ERROR-NO-LOG): negates `lg.warns.load(core::sync::atomic::Ordering::SeqCst) == 0`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_batch_touch_error_no_log__mutant() {
    let c = component();
    let a = c.create_pool(); // logs a debug IF a logger is connected — so connect after
    let lg = attach_logger(&c);
    assert!(lg.total() == 0);

    let ha = track_ok(&c, a, A); // track's SUCCESS path has no log site
    assert!(lg.total() == 0);

    let bad: PoolId = kani::any();
    kani::assume(bad != a);

    let r = c.batch_touch(&[ha, EvictionHandle::new(bad, 0)]);
    assert!(is_invalid_pool(&r, bad));
    // Silent: an operator reading the log cannot see that a bad identifier arrived.
    assert!(lg.total() == 0);
    assert!(!(lg.warns.load(core::sync::atomic::Ordering::SeqCst) == 0)); // MUTANT: negated
}

/// Twin of `verify_epo_remove_pre_pool_exists` (EPO-REMOVE-PRE-POOL-EXISTS): negates `is_invalid_pool(&r, bad)`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_remove_pre_pool_exists__mutant() {
    let c = component();
    let p = c.create_pool();

    let h1 = track_ok(&c, p, A);
    let _h2 = track_ok(&c, p, B);

    remove_ok(&c, h1);
    assert!(c.len(p) == 1);
    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &[B]));

    // The slot field being unchecked is the subject of the refutations, not an assumption
    // here: presenting an already-removed but still-allocated slot is accepted silently.
    assert!(c.remove(h1).is_ok());
    assert!(c.len(p) == 1);

    let bad: PoolId = kani::any();
    kani::assume(bad != p);
    let r = c.remove(EvictionHandle::new(bad, 0));
    assert!(!(is_invalid_pool(&r, bad))); // MUTANT: negated
}

/// Twin of `verify_epo_remove_frame_sketch_unchanged` (EPO-REMOVE-FRAME-SKETCH-UNCHANGED): negates `keys_eq(&c.get_eviction_candidates(p, 4), &[B, A])`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_remove_frame_sketch_unchanged__mutant() {
    let c = component();
    let p = c.create_pool();

    let h_a = track_ok(&c, p, A); // estimate(A) = 1, list [A]
    remove_ok(&c, h_a); // list []
    assert!(c.len(p) == 0);

    let _h_b = track_ok(&c, p, B); // list [B], estimate(B) = 1

    let _h_a2 = track_ok(&c, p, A); // estimate(A) = 2 > 1 -> protected end
    assert!(c.len(p) == 2);
    assert!(!(keys_eq(&c.get_eviction_candidates(p, 4), &[B, A]))); // MUTANT: negated
}

/// Twin of `verify_epo_remove_error_invalid_pool` (EPO-REMOVE-ERROR-INVALID-POOL): negates `keys_eq(&c.get_eviction_candidates(p, 4), &before)`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_remove_error_invalid_pool__mutant() {
    let c = component();
    let p = c.create_pool();
    let _h1 = track_ok(&c, p, A);
    let _h2 = track_ok(&c, p, B);
    let before = c.get_eviction_candidates(p, 4);

    let bad: PoolId = kani::any();
    kani::assume(bad != p);
    let idx: u32 = kani::any();

    let r = c.remove(EvictionHandle::new(bad, idx));
    assert!(r.is_err());
    assert!(is_invalid_pool(&r, bad));

    assert!(c.len(p) == 2);
    assert!(!(keys_eq(&c.get_eviction_candidates(p, 4), &before))); // MUTANT: negated
}

/// Twin of `verify_epo_evict_pre_total` (EPO-EVICT-PRE-TOTAL): negates `r == Some(A)`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_evict_pre_total__mutant() {
    let c = component();
    let p = c.create_pool();
    let _h = track_ok(&c, p, A);

    let q: PoolId = kani::any();
    let r = c.identify_next_to_evict(q);

    if q == p {
        assert!(!(r == Some(A))); // MUTANT: negated
        assert!(c.len(p) == 0);
    } else {
        assert!(r.is_none());
        assert!(c.len(p) == 1);
    }
}

/// Twin of `verify_epo_evict_frame_sketch_and_counters` (EPO-EVICT-FRAME-SKETCH-AND-COUNTERS): negates `keys_eq(&c.get_eviction_candidates(p, 4), &[A, B])`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_evict_frame_sketch_and_counters__mutant() {
    let c = component();
    let p = c.create_pool();

    let _h1 = track_ok(&c, p, A); // [A], estimate(A) = 1
    let _h2 = track_ok(&c, p, B); // [B, A], estimate(B) = 1

    assert!(c.identify_next_to_evict(p) == Some(B)); // B evicted; its record must survive
    assert!(c.len(p) == 1);
    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &[A]));

    let _h3 = track_ok(&c, p, B); // estimate(B) = 2 > estimate(A) = 1 -> protected end
    assert!(!(keys_eq(&c.get_eviction_candidates(p, 4), &[A, B]))); // MUTANT: negated
}

/// Twin of `verify_epo_evict_frame_other_pools` (EPO-EVICT-FRAME-OTHER-POOLS): negates `keys_eq(&c.get_eviction_candidates(a, 4), &[B, A, A])`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_evict_frame_other_pools__mutant() {
    let c = component();
    let a = c.create_pool();
    let b = c.create_pool();

    let _ha1 = track_ok(&c, a, A);
    let _ha2 = track_ok(&c, a, B); // a: [B, A]
    let _hb1 = track_ok(&c, b, C);
    let _hb2 = track_ok(&c, b, D); // b: [D, C]
    let a_before = c.get_eviction_candidates(a, 4);
    assert!(keys_eq(&a_before, &[B, A]));

    assert!(c.identify_next_to_evict(b) == Some(D));

    assert!(c.len(a) == 2);
    assert!(keys_eq(&c.get_eviction_candidates(a, 4), &a_before));
    // a's estimator is untouched too: re-tracking A strictly beats head B, as it would
    // have before the eviction in b.
    let _ha3 = track_ok(&c, a, A);
    assert!(!(keys_eq(&c.get_eviction_candidates(a, 4), &[B, A, A]))); // MUTANT: negated
}

/// Twin of `verify_epo_evict_degrade_invalid_pool` (EPO-EVICT-DEGRADE-INVALID-POOL): negates `keys_eq(&c.get_eviction_candidates(p, 4), &[A])`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_evict_degrade_invalid_pool__mutant() {
    let c = component();
    let p = c.create_pool();
    let q = c.create_pool(); // a real pool that will stay empty
    let lg = attach_logger(&c);

    let _h = track_ok(&c, p, A);

    let bad: PoolId = kani::any();
    kani::assume(bad != p && bad != q);

    assert!(c.identify_next_to_evict(bad).is_none()); // never created
    assert!(c.identify_next_to_evict(q).is_none()); // real, but empty: same answer
    assert!(lg.total() == 0); // and nothing said about either

    // Nothing changed anywhere.
    assert!(c.len(p) == 1);
    assert!(c.len(q) == 0);
    assert!(!(keys_eq(&c.get_eviction_candidates(p, 4), &[A]))); // MUTANT: negated
}

/// Twin of `verify_epo_candidates_pre_total` (EPO-CANDIDATES-PRE-TOTAL): negates `c.len(p) == 2`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_candidates_pre_total__mutant() {
    let c = component();
    let p = c.create_pool();
    let _h1 = track_ok(&c, p, A);
    let _h2 = track_ok(&c, p, B);

    let q: PoolId = kani::any();
    let n: usize = kani::any();
    kani::assume(n <= 4);

    let v = c.get_eviction_candidates(q, n);
    assert!(v.len() <= n);
    if q == p {
        assert!(v.len() == if n < 2 { n } else { 2 });
    } else {
        assert!(v.len() == 0);
    }
    // Non-destructive, so the pool is still intact afterwards.
    assert!(!(c.len(p) == 2)); // MUTANT: negated
}

/// Twin of `verify_epo_candidates_degrade_invalid_pool` (EPO-CANDIDATES-DEGRADE-INVALID-POOL): negates `c.len(p) == 1`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_candidates_degrade_invalid_pool__mutant() {
    let c = component();
    let p = c.create_pool();
    let q = c.create_pool();
    let lg = attach_logger(&c);

    let _h = track_ok(&c, p, A);

    let bad: PoolId = kani::any();
    kani::assume(bad != p && bad != q);
    let n: usize = kani::any();
    kani::assume(n <= 4);

    assert!(c.get_eviction_candidates(bad, n).len() == 0);
    assert!(c.get_eviction_candidates(q, n).len() == 0);
    assert!(lg.total() == 0);
    assert!(!(c.len(p) == 1)); // MUTANT: negated
}

/// Twin of `verify_epo_len_pre_total` (EPO-LEN-PRE-TOTAL): negates `c.len(q) == n`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_len_pre_total__mutant() {
    let c = component();
    let p = c.create_pool();
    let _h = track_ok(&c, p, A);

    let q: PoolId = kani::any();
    let n = c.len(q);
    if q == p {
        assert!(n == 1);
    } else {
        assert!(n == 0);
    }
    // ... and asking again gives the same answer: the call changes nothing.
    assert!(!(c.len(q) == n)); // MUTANT: negated
}

/// Twin of `verify_epo_len_degrade_invalid_pool` (EPO-LEN-DEGRADE-INVALID-POOL): negates `c.len(p) == 1`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_len_degrade_invalid_pool__mutant() {
    let c = component();
    let p = c.create_pool();
    let q = c.create_pool();
    let lg = attach_logger(&c);

    let _h = track_ok(&c, p, A);

    let bad: PoolId = kani::any();
    kani::assume(bad != p && bad != q);

    assert!(c.len(bad) == 0);
    assert!(c.len(q) == 0);
    assert!(c.len(bad) == c.len(q)); // indistinguishable
    assert!(lg.total() == 0);
    assert!(!(c.len(p) == 1)); // MUTANT: negated
}

/// Twin of `verify_epo_clear_pre_total` (EPO-CLEAR-PRE-TOTAL): negates `c.len(p) == 0`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_clear_pre_total__mutant() {
    let c = component();
    let p = c.create_pool();
    let _h1 = track_ok(&c, p, A);
    let _h2 = track_ok(&c, p, B);

    c.clear_pool(p);
    assert!(c.len(p) == 0);

    // Already empty: accepted, and idempotent.
    c.clear_pool(p);
    assert!(c.len(p) == 0);

    // Any identifier at all, including ones never created.
    let q: PoolId = kani::any();
    c.clear_pool(q);
    assert!(!(c.len(p) == 0)); // MUTANT: negated
}

/// Twin of `verify_epo_clear_frame_preserves_sketch_and_counters` (EPO-CLEAR-FRAME-PRESERVES-SKETCH-AND-COUNTERS): negates `keys_eq(&c.get_eviction_candidates(p, 4), &[B, A])`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_clear_frame_preserves_sketch_and_counters__mutant() {
    let c = component();
    let p = c.create_pool();

    let _h1 = track_ok(&c, p, A); // estimate(A) = 1, [A]
    let _h2 = track_ok(&c, p, A); // estimate(A) = 2, tie -> [A, A]
    let _h3 = track_ok(&c, p, B); // estimate(B) = 1 <= 2 -> [B, A, A]
    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &[B, A, A]));

    c.clear_pool(p);
    assert!(c.len(p) == 0);

    let _h4 = track_ok(&c, p, B); // estimate(B) = 2; pool empty -> [B]
    let _h5 = track_ok(&c, p, A); // estimate(A) = 3 > 2 -> protected end

    // Only reachable if the estimator crossed the clear intact.
    assert!(c.len(p) == 2);
    assert!(!(keys_eq(&c.get_eviction_candidates(p, 4), &[B, A]))); // MUTANT: negated
}

/// Twin of `verify_epo_clear_post_retrack_admitted_at_mru` (EPO-CLEAR-POST-RETRACK-ADMITTED-AT-MRU): negates `c.len(p) == 0`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_clear_post_retrack_admitted_at_mru__mutant() {
    let c = component();
    let p = c.create_pool();

    let _h1 = track_ok(&c, p, A);
    let _h2 = track_ok(&c, p, A);
    let _h3 = track_ok(&c, p, A); // estimate(A) = 3, list [A, A, A]
    assert!(c.len(p) == 3);

    c.clear_pool(p);
    assert!(c.len(p) == 0);

    // Same identifier, immediately usable.
    let h4 = track_ok(&c, p, A);
    assert!(h4.pool_id() == p);
    assert!(c.len(p) == 1);
    // The only entry, so the protected end and the front at once.
    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &[A]));
    assert!(c.identify_next_to_evict(p) == Some(A));
    assert!(!(c.len(p) == 0)); // MUTANT: negated
}

/// Twin of `verify_epo_clear_frame_other_pools` (EPO-CLEAR-FRAME-OTHER-POOLS): negates `c.create_pool() == b + 1`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_clear_frame_other_pools__mutant() {
    let c = component();
    let a = c.create_pool();
    let b = c.create_pool();

    let _ha1 = track_ok(&c, a, A);
    let _ha2 = track_ok(&c, a, B); // a: [B, A]
    let _hb = track_ok(&c, b, C); // b: [C]
    let a_before = c.get_eviction_candidates(a, 4);
    assert!(keys_eq(&a_before, &[B, A]));

    c.clear_pool(b);

    // a is untouched, in entries and in order ...
    assert!(c.len(a) == 2);
    assert!(keys_eq(&c.get_eviction_candidates(a, 4), &a_before));
    // ... and a's estimator too: re-tracking A strictly beats head B.
    let _ha3 = track_ok(&c, a, A);
    assert!(keys_eq(&c.get_eviction_candidates(a, 4), &[B, A, A]));

    // b was emptied, not removed: it still exists under the same identifier and works.
    assert!(c.len(b) == 0);
    let hb2 = track_ok(&c, b, D);
    assert!(hb2.pool_id() == b);
    assert!(c.len(b) == 1);
    // No renumbering: the next identifier continues the sequence.
    assert!(!(c.create_pool() == b + 1)); // MUTANT: negated
}

/// Twin of `verify_epo_clear_degrade_invalid_pool` (EPO-CLEAR-DEGRADE-INVALID-POOL): negates `keys_eq(&c.get_eviction_candidates(p, 4), &[A])`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_clear_degrade_invalid_pool__mutant() {
    let c = component();
    let p = c.create_pool();
    let lg = attach_logger(&c);

    let _h = track_ok(&c, p, A);

    let bad: PoolId = kani::any();
    kani::assume(bad != p);

    c.clear_pool(bad); // silently ignored

    assert!(lg.total() == 0);
    assert!(c.len(p) == 1);
    assert!(!(keys_eq(&c.get_eviction_candidates(p, 4), &[A]))); // MUTANT: negated
}

/// Twin of `verify_epo_inv_pool_ids_unique_sequential` (EPO-INV-POOL-IDS-UNIQUE-SEQUENTIAL): negates `c.len(p0) == 0 && c.len(p1) == 0 && c.len(p2) == 0`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_inv_pool_ids_unique_sequential__mutant() {
    let c = component();
    let p0 = c.create_pool();
    let p1 = c.create_pool();
    let p2 = c.create_pool();

    // A gapless sequence from zero, no repeats.
    assert!(p0 == 0 && p1 == 1 && p2 == 2);
    assert!(c.len(p0) == 0 && c.len(p1) == 0 && c.len(p2) == 0);

    let q: PoolId = kani::any();
    kani::assume(q > p2);

    // Reported ...
    let r = c.track(q, A, sem());
    assert!(is_invalid_pool(&r, q));
    let rb = c.batch_touch(&[EvictionHandle::new(q, 0)]);
    assert!(is_invalid_pool(&rb, q));
    // ... or silently treated as empty.
    assert!(c.len(q) == 0);
    assert!(c.identify_next_to_evict(q).is_none());
    assert!(c.get_eviction_candidates(q, 4).len() == 0);
    c.clear_pool(q);

    // None of that created anything.
    assert!(!(c.len(p0) == 0 && c.len(p1) == 0 && c.len(p2) == 0)); // MUTANT: negated
}

/// Twin of `verify_epo_inv_pools_append_only` (EPO-INV-POOLS-APPEND-ONLY): negates `c.track(q, D, sem()).is_err()`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_inv_pools_append_only__mutant() {
    let c = component();
    let a = c.create_pool();

    let h = track_ok(&c, a, A);
    remove_ok(&c, h); // emptied by removal
    let b = c.create_pool();
    assert!(b == a + 1);

    let h2 = track_ok(&c, a, B);
    assert!(c.identify_next_to_evict(a) == Some(B)); // emptied by eviction
    let _ = h2;
    c.clear_pool(a); // emptied by clear

    let d = c.create_pool();
    assert!(d == b + 1); // no recycling, no renumbering

    // `a` is still valid, and still means the same pool.
    assert!(c.len(a) == 0);
    let h3 = track_ok(&c, a, C);
    assert!(h3.pool_id() == a);
    assert!(c.len(a) == 1);

    // An identifier never returned stays invalid.
    let q: PoolId = kani::any();
    kani::assume(q > d);
    assert!(!(c.track(q, D, sem()).is_err())); // MUTANT: negated
}

/// Twin of `verify_epo_inv_pool_isolation` (EPO-INV-POOL-ISOLATION): negates `keys_eq(&c.get_eviction_candidates(a, 4), &[B, A, A])`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_inv_pool_isolation__mutant() {
    let c = component();
    let a = c.create_pool();
    let b = c.create_pool();

    let _ha1 = track_ok(&c, a, A);
    let _ha2 = track_ok(&c, a, B); // a: [B, A]
    let _hb1 = track_ok(&c, b, C); // b: [C]
    let a_before = c.get_eviction_candidates(a, 4);
    assert!(keys_eq(&a_before, &[B, A]));

    // The battery, all on b.
    let hb2 = track_ok(&c, b, D); // b: [D, C]
    touch_ok(&c, hb2); // b: [C, D]
    remove_ok(&c, hb2); // b: [C]
    assert!(c.identify_next_to_evict(b) == Some(C)); // b: []
    c.clear_pool(b);
    assert!(c.len(b) == 0);

    // a is untouched in entries and order ...
    assert!(c.len(a) == 2);
    assert!(keys_eq(&c.get_eviction_candidates(a, 4), &a_before));
    // ... and in what it believes about popularity.
    let _ha3 = track_ok(&c, a, A);
    assert!(!(keys_eq(&c.get_eviction_candidates(a, 4), &[B, A, A]))); // MUTANT: negated
}

/// Twin of `verify_epo_inv_handle_pool_scoped` (EPO-INV-HANDLE-POOL-SCOPED): negates `ha2.pool_id() == a && hb2.pool_id() == b`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_inv_handle_pool_scoped__mutant() {
    let c = component();
    let a = c.create_pool();
    let b = c.create_pool();

    let ha = track_ok(&c, a, A);
    let hb = track_ok(&c, b, B);

    // Same position, different pools — the only thing telling them apart is the pool field.
    assert!(ha.index() == hb.index());
    assert!(ha.pool_id() == a && hb.pool_id() == b && a != b);

    remove_ok(&c, ha);
    assert!(c.len(a) == 0);
    assert!(c.len(b) == 1);
    assert!(keys_eq(&c.get_eviction_candidates(b, 4), &[B]));

    // Touching through b's handle affects b only.
    touch_ok(&c, hb);
    assert!(c.len(a) == 0 && c.len(b) == 1);

    // Every issued handle names the pool it was tracked into.
    let ha2 = track_ok(&c, a, C);
    let hb2 = track_ok(&c, b, D);
    assert!(!(ha2.pool_id() == a && hb2.pool_id() == b)); // MUTANT: negated
}

/// Twin of `verify_epo_inv_invalid_handle_never_returned` (EPO-INV-INVALID-HANDLE-NEVER-RETURNED): negates `c.len(p) == 1`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_inv_invalid_handle_never_returned__mutant() {
    let c = component();
    let p = c.create_pool();

    let h1 = track_ok(&c, p, A);
    let _h2 = track_ok(&c, p, B);

    let bad: PoolId = kani::any();
    kani::assume(bad != p);
    let idx: u32 = kani::any();
    let bh = EvictionHandle::new(bad, idx);

    // Bad pool: invalid-POOL, never invalid-HANDLE, on every fallible method.
    let r1 = c.track(bad, A, sem());
    assert!(is_invalid_pool(&r1, bad));
    let r2 = c.touch(bh);
    assert!(is_invalid_pool(&r2, bad));
    let r3 = c.remove(bh);
    assert!(is_invalid_pool(&r3, bad));
    let r4 = c.batch_touch(&[bh]);
    assert!(is_invalid_pool(&r4, bad));

    // An already-removed handle — the interface's own use case for InvalidHandle — is
    // accepted silently instead of reported.
    remove_ok(&c, h1);
    assert!(c.touch(h1).is_ok());
    assert!(c.remove(h1).is_ok());
    assert!(c.batch_touch(&[h1]).is_ok());
    assert!(!(c.len(p) == 1)); // MUTANT: negated
}

/// Twin of `verify_epo_inv_maxlen_monotone` (EPO-INV-MAXLEN-MONOTONE): negates `keys_eq(&c.get_eviction_candidates(p, 4), &[C])`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_inv_maxlen_monotone__mutant() {
    // --- the only write, mirrored from lib.rs:122 ---
    let ml: usize = kani::any();
    let len: usize = kani::any();
    kani::assume(ml <= (1usize << 40) && len <= (1usize << 40));
    assert!(ml.max(len) >= ml); // it can only stay the same or grow

    // --- the three operations the statement names, against the real component ---
    let c = component();
    let p = c.create_pool();
    let h1 = track_ok(&c, p, A);
    let _h2 = track_ok(&c, p, B);
    assert!(c.len(p) == 2);

    remove_ok(&c, h1);
    assert!(c.len(p) == 1);
    assert!(c.identify_next_to_evict(p) == Some(B));
    assert!(c.len(p) == 0);
    c.clear_pool(p);
    assert!(c.len(p) == 0);

    // Still usable afterwards, so nothing was corrupted by the sequence.
    let _h3 = track_ok(&c, p, C);
    assert!(c.len(p) == 1);
    assert!(!(keys_eq(&c.get_eviction_candidates(p, 4), &[C]))); // MUTANT: negated
}

/// Twin of `verify_epo_inv_access_count_monotone` (EPO-INV-ACCESS-COUNT-MONOTONE): negates `keys_eq(&c.get_eviction_candidates(p, 4), &[A, B])`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_inv_access_count_monotone__mutant() {
    // --- the only write, mirrored from lib.rs:123 ---
    let ac: u64 = kani::any();
    // A track allocates a `Node`, so the tally is bounded by the number of allocations a
    // process can make; 2^48 is far above that and far below u64::MAX, so `+= 1` is exact.
    kani::assume(ac < (1u64 << 48));
    assert!(ac.checked_add(1).is_some());
    assert!(ac + 1 > ac);

    // --- the real component across a clear ---
    let c = component();
    let p = c.create_pool();
    let _h1 = track_ok(&c, p, A);
    let _h2 = track_ok(&c, p, B);
    assert!(c.len(p) == 2);

    c.clear_pool(p);
    assert!(c.len(p) == 0);

    // The pool is the same pool, still tracking into the same bookkeeping — and what it
    // learned about A survives the clear, which is the observable sibling of the tally
    // surviving it (see verify_epo_clear_frame_preserves_sketch_and_counters).
    let _h3 = track_ok(&c, p, B); // estimate(B) = 2; empty pool -> protected end
    let _h4 = track_ok(&c, p, A); // estimate(A) = 2 <= 2 -> eviction end
    assert!(!(keys_eq(&c.get_eviction_candidates(p, 4), &[A, B]))); // MUTANT: negated
}

/// Twin of `verify_epo_inv_at_most_one_pool_lock` (EPO-INV-AT-MOST-ONE-POOL-LOCK): negates `c.len(a) == 0 && c.len(b) == 0`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_inv_at_most_one_pool_lock__mutant() {
    let c = component();
    let a = c.create_pool();
    let b = c.create_pool();

    let ha = track_ok(&c, a, A);
    let hb = track_ok(&c, b, B);

    // Alternating pools: a, then b, then a again — two pool changes inside one call.
    batch_ok(&c, &[ha, hb, ha]);
    assert!(c.len(a) == 1 && c.len(b) == 1);
    assert!(keys_eq(&c.get_eviction_candidates(a, 4), &[A]));
    assert!(keys_eq(&c.get_eviction_candidates(b, 4), &[B]));

    // Each single-pool method takes at most one pool lock, structurally: one
    // `state.pools.get(..)` followed by one `lock()`. All of them complete in sequence.
    touch_ok(&c, ha);
    assert!(c.identify_next_to_evict(b) == Some(B));
    remove_ok(&c, ha);
    c.clear_pool(a);
    assert!(!(c.len(a) == 0 && c.len(b) == 0)); // MUTANT: negated
}

/// Twin of `verify_epo_inv_logger_optional` (EPO-INV-LOGGER-OPTIONAL): negates `lg.total() == 0`. Must FAIL.
#[kani::proof]
#[kani::stub(std::collections::hash_map::RandomState::new, crate::api::concrete_state)]
#[kani::unwind(4)]
#[kani::solver(minisat)]
fn verify_epo_inv_logger_optional__mutant() {
    let c = component();
    let p = c.create_pool(); // before any connection: its debug site is not evaluated

    let connected: bool = kani::any();
    let lg = new_counting_logger();
    if connected {
        connect_logger(&c, &lg);
    }
    assert!(c.logger.is_connected() == connected);
    assert!(c.logger.get().is_ok() == connected);

    // One script, a fixed expected answer at every step, for both values of `connected`.
    let h1 = track_ok(&c, p, A);
    let h2 = track_ok(&c, p, B);
    assert!(c.len(p) == 2);
    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &[B, A]));

    touch_ok(&c, h2);
    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &[A, B]));

    batch_ok(&c, &[h1]);
    assert!(keys_eq(&c.get_eviction_candidates(p, 4), &[B, A]));

    remove_ok(&c, h1);
    assert!(c.len(p) == 1);
    assert!(c.identify_next_to_evict(p) == Some(B));
    assert!(c.len(p) == 0);

    c.clear_pool(p);
    assert!(c.len(p) == 0);

    // None of those eight methods logs on its success path, so nothing was written even
    // when a logger was there to receive it.
    assert!(!(lg.total() == 0)); // MUTANT: negated
}
