# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dispatcher_pb2 as dispatcher__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dispatcher_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DispatcherStub(object):
    """Service exposing IDispatcher data operations as batch-capable RPCs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Populate = channel.unary_unary(
                '/certus.dispatcher.v1.Dispatcher/Populate',
                request_serializer=dispatcher__pb2.BatchPopulateRequest.SerializeToString,
                response_deserializer=dispatcher__pb2.BatchPopulateResponse.FromString,
                _registered_method=True)
        self.Lookup = channel.unary_unary(
                '/certus.dispatcher.v1.Dispatcher/Lookup',
                request_serializer=dispatcher__pb2.BatchLookupRequest.SerializeToString,
                response_deserializer=dispatcher__pb2.BatchLookupResponse.FromString,
                _registered_method=True)
        self.Check = channel.unary_unary(
                '/certus.dispatcher.v1.Dispatcher/Check',
                request_serializer=dispatcher__pb2.BatchCheckRequest.SerializeToString,
                response_deserializer=dispatcher__pb2.BatchCheckResponse.FromString,
                _registered_method=True)
        self.Remove = channel.unary_unary(
                '/certus.dispatcher.v1.Dispatcher/Remove',
                request_serializer=dispatcher__pb2.BatchRemoveRequest.SerializeToString,
                response_deserializer=dispatcher__pb2.BatchRemoveResponse.FromString,
                _registered_method=True)
        self.Touch = channel.unary_unary(
                '/certus.dispatcher.v1.Dispatcher/Touch',
                request_serializer=dispatcher__pb2.BatchTouchRequest.SerializeToString,
                response_deserializer=dispatcher__pb2.BatchTouchResponse.FromString,
                _registered_method=True)
        self.Reserve = channel.unary_unary(
                '/certus.dispatcher.v1.Dispatcher/Reserve',
                request_serializer=dispatcher__pb2.BatchReserveRequest.SerializeToString,
                response_deserializer=dispatcher__pb2.BatchReserveResponse.FromString,
                _registered_method=True)
        self.CopyToStore = channel.unary_unary(
                '/certus.dispatcher.v1.Dispatcher/CopyToStore',
                request_serializer=dispatcher__pb2.BatchCopyToStoreRequest.SerializeToString,
                response_deserializer=dispatcher__pb2.BatchCopyToStoreResponse.FromString,
                _registered_method=True)
        self.CommitStore = channel.unary_unary(
                '/certus.dispatcher.v1.Dispatcher/CommitStore',
                request_serializer=dispatcher__pb2.BatchCommitStoreRequest.SerializeToString,
                response_deserializer=dispatcher__pb2.BatchCommitStoreResponse.FromString,
                _registered_method=True)
        self.AbortStore = channel.unary_unary(
                '/certus.dispatcher.v1.Dispatcher/AbortStore',
                request_serializer=dispatcher__pb2.BatchAbortStoreRequest.SerializeToString,
                response_deserializer=dispatcher__pb2.BatchAbortStoreResponse.FromString,
                _registered_method=True)
        self.ClearMemoryTier = channel.unary_unary(
                '/certus.dispatcher.v1.Dispatcher/ClearMemoryTier',
                request_serializer=dispatcher__pb2.ClearMemoryTierRequest.SerializeToString,
                response_deserializer=dispatcher__pb2.ClearMemoryTierResponse.FromString,
                _registered_method=True)
        self.FlushToSsd = channel.unary_unary(
                '/certus.dispatcher.v1.Dispatcher/FlushToSsd',
                request_serializer=dispatcher__pb2.FlushToSsdRequest.SerializeToString,
                response_deserializer=dispatcher__pb2.FlushToSsdResponse.FromString,
                _registered_method=True)
        self.Pin = channel.unary_unary(
                '/certus.dispatcher.v1.Dispatcher/Pin',
                request_serializer=dispatcher__pb2.BatchPinRequest.SerializeToString,
                response_deserializer=dispatcher__pb2.BatchPinResponse.FromString,
                _registered_method=True)
        self.Unpin = channel.unary_unary(
                '/certus.dispatcher.v1.Dispatcher/Unpin',
                request_serializer=dispatcher__pb2.BatchUnpinRequest.SerializeToString,
                response_deserializer=dispatcher__pb2.BatchUnpinResponse.FromString,
                _registered_method=True)
        self.TakeEvents = channel.unary_unary(
                '/certus.dispatcher.v1.Dispatcher/TakeEvents',
                request_serializer=dispatcher__pb2.TakeEventsRequest.SerializeToString,
                response_deserializer=dispatcher__pb2.TakeEventsResponse.FromString,
                _registered_method=True)


class DispatcherServicer(object):
    """Service exposing IDispatcher data operations as batch-capable RPCs.
    """

    def Populate(self, request, context):
        """Populate cache entries by DMA-copying from GPU memory.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lookup(self, request, context):
        """Look up cache entries and DMA-copy data to client GPU memory.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Check(self, request, context):
        """Check whether cache entries exist without transferring data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Remove cache entries, freeing associated resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Touch(self, request, context):
        """Touch cache entries, updating eviction timestamps without DMA.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reserve(self, request, context):
        """Reserve memory-tier slots for split-phase store (no DMA, no dispatch-map registration).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CopyToStore(self, request, context):
        """DMA-copy from GPU into previously reserved slots (server synchronizes stream internally).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitStore(self, request, context):
        """Finalize reserved slots: register in dispatch-map and enqueue SSD write-through.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortStore(self, request, context):
        """Cancel reserved slots without populating (idempotent).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearMemoryTier(self, request, context):
        """Clear all entries from the memory-tier cache pool.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FlushToSsd(self, request, context):
        """Flush all pending background write-through jobs to SSD and block until done.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pin(self, request, context):
        """Pin cache entries: increment reference count to prevent eviction.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unpin(self, request, context):
        """Unpin cache entries: decrement reference count, allowing eviction when zero.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TakeEvents(self, request, context):
        """Drain eviction events since the last call (non-blocking poll).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DispatcherServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Populate': grpc.unary_unary_rpc_method_handler(
                    servicer.Populate,
                    request_deserializer=dispatcher__pb2.BatchPopulateRequest.FromString,
                    response_serializer=dispatcher__pb2.BatchPopulateResponse.SerializeToString,
            ),
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=dispatcher__pb2.BatchLookupRequest.FromString,
                    response_serializer=dispatcher__pb2.BatchLookupResponse.SerializeToString,
            ),
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=dispatcher__pb2.BatchCheckRequest.FromString,
                    response_serializer=dispatcher__pb2.BatchCheckResponse.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=dispatcher__pb2.BatchRemoveRequest.FromString,
                    response_serializer=dispatcher__pb2.BatchRemoveResponse.SerializeToString,
            ),
            'Touch': grpc.unary_unary_rpc_method_handler(
                    servicer.Touch,
                    request_deserializer=dispatcher__pb2.BatchTouchRequest.FromString,
                    response_serializer=dispatcher__pb2.BatchTouchResponse.SerializeToString,
            ),
            'Reserve': grpc.unary_unary_rpc_method_handler(
                    servicer.Reserve,
                    request_deserializer=dispatcher__pb2.BatchReserveRequest.FromString,
                    response_serializer=dispatcher__pb2.BatchReserveResponse.SerializeToString,
            ),
            'CopyToStore': grpc.unary_unary_rpc_method_handler(
                    servicer.CopyToStore,
                    request_deserializer=dispatcher__pb2.BatchCopyToStoreRequest.FromString,
                    response_serializer=dispatcher__pb2.BatchCopyToStoreResponse.SerializeToString,
            ),
            'CommitStore': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitStore,
                    request_deserializer=dispatcher__pb2.BatchCommitStoreRequest.FromString,
                    response_serializer=dispatcher__pb2.BatchCommitStoreResponse.SerializeToString,
            ),
            'AbortStore': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortStore,
                    request_deserializer=dispatcher__pb2.BatchAbortStoreRequest.FromString,
                    response_serializer=dispatcher__pb2.BatchAbortStoreResponse.SerializeToString,
            ),
            'ClearMemoryTier': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearMemoryTier,
                    request_deserializer=dispatcher__pb2.ClearMemoryTierRequest.FromString,
                    response_serializer=dispatcher__pb2.ClearMemoryTierResponse.SerializeToString,
            ),
            'FlushToSsd': grpc.unary_unary_rpc_method_handler(
                    servicer.FlushToSsd,
                    request_deserializer=dispatcher__pb2.FlushToSsdRequest.FromString,
                    response_serializer=dispatcher__pb2.FlushToSsdResponse.SerializeToString,
            ),
            'Pin': grpc.unary_unary_rpc_method_handler(
                    servicer.Pin,
                    request_deserializer=dispatcher__pb2.BatchPinRequest.FromString,
                    response_serializer=dispatcher__pb2.BatchPinResponse.SerializeToString,
            ),
            'Unpin': grpc.unary_unary_rpc_method_handler(
                    servicer.Unpin,
                    request_deserializer=dispatcher__pb2.BatchUnpinRequest.FromString,
                    response_serializer=dispatcher__pb2.BatchUnpinResponse.SerializeToString,
            ),
            'TakeEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.TakeEvents,
                    request_deserializer=dispatcher__pb2.TakeEventsRequest.FromString,
                    response_serializer=dispatcher__pb2.TakeEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'certus.dispatcher.v1.Dispatcher', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('certus.dispatcher.v1.Dispatcher', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Dispatcher(object):
    """Service exposing IDispatcher data operations as batch-capable RPCs.
    """

    @staticmethod
    def Populate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/certus.dispatcher.v1.Dispatcher/Populate',
            dispatcher__pb2.BatchPopulateRequest.SerializeToString,
            dispatcher__pb2.BatchPopulateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/certus.dispatcher.v1.Dispatcher/Lookup',
            dispatcher__pb2.BatchLookupRequest.SerializeToString,
            dispatcher__pb2.BatchLookupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/certus.dispatcher.v1.Dispatcher/Check',
            dispatcher__pb2.BatchCheckRequest.SerializeToString,
            dispatcher__pb2.BatchCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/certus.dispatcher.v1.Dispatcher/Remove',
            dispatcher__pb2.BatchRemoveRequest.SerializeToString,
            dispatcher__pb2.BatchRemoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Touch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/certus.dispatcher.v1.Dispatcher/Touch',
            dispatcher__pb2.BatchTouchRequest.SerializeToString,
            dispatcher__pb2.BatchTouchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reserve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/certus.dispatcher.v1.Dispatcher/Reserve',
            dispatcher__pb2.BatchReserveRequest.SerializeToString,
            dispatcher__pb2.BatchReserveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CopyToStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/certus.dispatcher.v1.Dispatcher/CopyToStore',
            dispatcher__pb2.BatchCopyToStoreRequest.SerializeToString,
            dispatcher__pb2.BatchCopyToStoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/certus.dispatcher.v1.Dispatcher/CommitStore',
            dispatcher__pb2.BatchCommitStoreRequest.SerializeToString,
            dispatcher__pb2.BatchCommitStoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/certus.dispatcher.v1.Dispatcher/AbortStore',
            dispatcher__pb2.BatchAbortStoreRequest.SerializeToString,
            dispatcher__pb2.BatchAbortStoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearMemoryTier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/certus.dispatcher.v1.Dispatcher/ClearMemoryTier',
            dispatcher__pb2.ClearMemoryTierRequest.SerializeToString,
            dispatcher__pb2.ClearMemoryTierResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FlushToSsd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/certus.dispatcher.v1.Dispatcher/FlushToSsd',
            dispatcher__pb2.FlushToSsdRequest.SerializeToString,
            dispatcher__pb2.FlushToSsdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/certus.dispatcher.v1.Dispatcher/Pin',
            dispatcher__pb2.BatchPinRequest.SerializeToString,
            dispatcher__pb2.BatchPinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unpin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/certus.dispatcher.v1.Dispatcher/Unpin',
            dispatcher__pb2.BatchUnpinRequest.SerializeToString,
            dispatcher__pb2.BatchUnpinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TakeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/certus.dispatcher.v1.Dispatcher/TakeEvents',
            dispatcher__pb2.TakeEventsRequest.SerializeToString,
            dispatcher__pb2.TakeEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
